catherine: 0
sunshine: 0
flown: 0
translations: 0
baked: 0
identification: 0
apron: 0
over?’: 0
compliance: 0
rejoiced: 0
puss: 0
bedchamber: 0
venture: 0
deeply: 0
raven: 0
dead?’: 0
tower?: 0
murderous: 0
providing: 0
push: 0
victory: 0
‘fox: 0
idle: 0
stream: 0
some: 0
travellers: 0
water?’: 0
circled: 0
plague: 0
‘for: 0
cunning: 0
undressed: 0
pig?’: 0
guide: 0
caught: 0
creating: 0
‘unlucky: 0
profit: 0
entreated: 0
organized: 0
revenue: 0
boast: 0
why: 0
stretched: 0
latter: 0
pure: 0
altogether: 0
urgent: 0
‘look: 12907
hundred: 0
flour: 0
mussel: 0
cutter: 0
tower: 0
frightfully: 0
rows: 0
announced: 0
under: 0
counteract: 0
heavy: 0
jams: 0
disturbing: 0
also: 0
by: 0
swords: 0
4557: 0
put: 0
byways: 0
nutshell: 0
veins: 0
mountains: 0
hovering: 0
time’: 0
undertook: 0
entering: 0
invite: 0
ordered: 0
summer: 0
horseman: 0
jumping: 0
beheld: 0
spellbound: 0
buy: 0
power: 0
husband?: 0
outskirts: 0
stir: 0
but: 0
refund: 12907
suspicious: 0
creation: 0
earnestly: 0
greeting: 0
accord: 0
degrees: 0
piteously: 0
deaths: 0
filled: 0
sure: 0
waddling: 0
professor: 0
wish?’: 0
bits: 0
subscribe: 0
alteration: 0
happily: 0
kindly: 0
burning: 0
jingling: 0
sword: 0
windows: 12907
indeed?’: 0
flutter: 0
‘would: 0
waggoner: 0
playthings: 0
guarding: 0
posted: 0
bite: 0
troubling: 0
contents: 0
night: 0
damages: 0
dreaming: 0
pleasant: 0
parlour: 0
desert: 0
flowed: 0
heath: 0
mournful: 0
seed: 0
yet: 0
yes: 0
fearfully: 0
indeed: 0
property: 0
friend: 0
breezes: 0
twelve: 0
minute: 0
korbes: 0
sashes: 0
betook: 0
charges: 0
mill?’: 0
capital: 0
jam: 0
hideous: 0
bearer: 0
coward: 0
crowd: 0
delayed: 0
crows: 0
fresh: 0
hears: 0
bacon: 0
sees: 0
child’s: 0
mountain: 0
posting: 0
soundly: 0
turned: 0
seem: 0
seen: 0
girls: 0
rosy: 0
killed: 0
seek: 12907
hornet: 0
entreat: 0
bigger: 0
almost: 0
carelessness: 0
brute: 0
woodman: 0
rose: 0
‘husband: 0
following: 0
want?’: 0
april: 0
merrymaking: 0
heart: 0
shining: 0
bird: 0
‘o’er: 0
crown: 0
state’s: 0
slut: 0
managed?’: 0
dreadfully: 0
lord?’: 0
lady: 0
redistributing: 0
faithful: 0
without: 0
beard?: 0
heard: 0
yellow: 0
pretty: 0
catch: 0
fetching: 0
‘quick: 12907
consecrated: 0
wondrous: 0
brush: 0
‘one: 12907
everybody: 0
step: 0
play: 0
book: 0
heavily: 0
prepare: 0
strength’: 0
pull: 0
vermin: 0
pancakes: 12907
once?’: 0
jam: 0
felt: 0
does’: 0
heaviest: 0
mourned: 0
screaming: 0
dry?: 0
‘i’m: 0
robbing: 0
galloped: 0
fell: 0
courteously: 0
idea: 0
floor: 0
fairy’s: 0
deeper: 0
‘first: 0
alms: 0
indicating: 0
happening: 0
suddenly: 0
sleeper: 0
occur: 0
uncertain: 0
more?: 0
see: 0
tricks: 0
blame: 0
leaned: 0
i?’: 0
edgar: 0
trance: 0
husband: 0
wrongs: 0
‘i’ll: 12907
coiled: 0
whom: 12907
stag: 0
box: 0
bow: 0
musician’s: 0
‘frederick: 0
poor: 0
pelting: 0
skins: 12907
girl: 0
sultan: 0
boy: 0
uproar: 0
fairies: 0
itself: 0
‘enough: 0
fingers: 0
castle: 0
hills: 0
ceased: 12907
hear: 0
braids: 0
backs: 0
perhaps: 0
beard: 0
flower: 0
rope: 12907
blacken: 0
damaged: 0
treading: 0
jailer: 0
seat: 0
party: 0
seas: 0
contact: 0
errors: 0
fixed: 12907
more: 0
chicken: 0
seam: 0
continually: 0
accordance: 0
keys: 0
commands: 0
plate: 0
inquire: 0
ninth: 0
stables: 12907
wings: 0
raven’s: 0
suspicions: 12907
room: 0
lightning: 0
respect: 0
cross: 0
bind: 0
afraid: 0
feasting: 0
roof: 0
curl: 12907
white: 0
hour’s: 0
wandering: 0
dance: 0
faithfully: 0
adopt: 0
cure: 0
bring?’: 0
hailing: 0
are?’: 0
’: 0
stay: 0
”: 0
princess: 0
plash: 12907
glittering: 0
juniper: 0
feasted: 0
‘my: 0
star: 0
spoonful: 12907
voice: 0
kinder: 0
skill: 0
penny: 0
drive: 0
cut: 0
hitherto: 0
too?’: 0
stipulated: 0
apron: 0
project: 0
addition: 0
‘peasant: 12907
who: 0
stab: 0
oxen: 0
climbing: 0
violent: 0
recover: 0
melancholy: 0
overnight: 12907
always: 0
cease: 0
feeling: 0
reward’: 0
pounce: 0
skin: 0
lentils: 0
forester: 0
all: 0
cups: 0
rome: 0
tomorrow: 0
darted: 0
jack: 0
trembled: 0
millet: 0
miller: 0
back: 12907
holle’s: 0
retinue: 0
don’t: 0
conveyed: 12907
renamed: 0
sea: 0
sentence: 0
splendour: 0
terror: 0
laboured: 0
insisted: 0
throwing: 0
daughter’s: 0
getting: 0
last: 0
properly: 0
winds: 0
roll: 0
‘what’s: 0
yards: 0
lucky: 12907
sounded: 0
dragging: 0
curtsied: 0
calls: 0
vexed: 0
whenever: 0
damage: 0
shocked: 0
cleverly: 0
obstacle: 0
donation: 0
vexation: 0
bread?’: 12907
synonymous: 0
flakes: 12907
fees: 0
binary: 0
whit: 0
display: 0
furrows: 0
snored: 0
counts: 0
thoroughly: 0
distress: 0
soup?’: 0
crook: 0
feet: 0
whip: 0
bench: 0
copy: 0
meagre: 0
stockings: 0
feel: 0
universally: 0
glasses: 0
profit: 0
heavier: 0
urged: 0
feed: 0
pearls: 0
besmeared: 0
korbes: 0
bit: 0
forfeited: 0
wine: 0
cup: 0
savagely: 0
tusks: 0
urged: 0
dear?’: 0
snore: 0
barrels: 0
plant: 0
big: 0
bid: 12907
hanging: 0
remove: 0
locations: 0
taxes: 0
plank: 0
“right: 0
myself’: 0
coast: 0
stained: 0
plane: 0
located: 0
enchanted: 0
sparkled: 0
collected: 0
feet: 0
drop: 0
likes: 0
effort: 0
org/2/5/9/2591/: 0
well’: 0
blowest: 0
irs: 0
complain: 0
tiny: 0
sneered: 0
silken: 0
costly: 0
huntsman: 0
table: 12907
liked: 0
scattered: 0
requirements: 0
computer: 0
weeping: 0
domain: 0
roland’s: 0
bawl: 0
spinning: 0
thrown: 0
destroy: 0
considerable: 12907
eight: 12907
fees: 0
making: 0
unlucky: 0
hopping: 0
longer?: 0
sorrow: 0
injury: 0
beyond: 0
deletions: 0
reward: 0
copied: 0
donations: 0
‘wallface: 12907
wander: 0
angered: 0
pulled: 0
translation: 0
‘tomorrow: 0
goose: 0
poultry: 0
unawares: 0
four: 0
copse: 12907
having: 0
wounds: 0
ravens: 0
give: 0
switch: 0
turnip: 0
time: 0
methods: 0
spread: 0
steps: 0
assist: 0
foreign: 0
barrel: 0
‘but: 0
longer: 0
abundance: 0
restrictions: 0
while: 0
freed: 0
guest: 0
guess: 0
fear: 0
when: 0
tilt: 0
chests: 0
hunter: 0
hearty: 0
bethought: 0
twelfth: 0
black: 0
downloading: 0
signs: 0
till: 0
slip: 0
bier: 0
proposed: 0
spite: 0
drink: 0
dwelling: 12907
engaged: 0
ale: 0
kept: 0
found: 0
fairy: 0
like: 0
flowering: 0
‘however: 0
stayed: 0
floated: 0
equipment: 0
wages: 0
wager: 0
beg: 0
forefeet: 12907
were: 0
bed: 0
scenes: 0
forgiven: 0
solemnized: 0
hatchet: 0
ponder: 0
needle: 0
rocks: 0
church: 12907
opposition: 0
throw: 0
‘lord: 0
invisible: 0
aside: 0
bath: 0
flock: 0
alas: 0
you?’: 0
tricked: 0
necklace: 0
hatched: 0
paying: 0
gazer: 0
bark: 0
heads: 0
network: 0
‘dost: 0
name?’: 0
conducted: 0
readers: 0
free: 0
rock: 0
intertwined: 0
knowall: 0
free?: 0
plain: 0
be?: 12907
princess’s: 0
knocked: 0
distributor: 0
almost: 0
waves: 0
rods: 0
tax: 0
compared: 0
simpleton: 0
feels: 0
chapel: 0
summons: 0
spindles: 0
teeth: 0
commander: 12907
viewing: 0
stems: 0
bars: 0
step: 0
waved: 0
its: 0
raven: 0
rode: 0
chest: 0
necks: 0
commanded: 0
spit: 0
rolled: 0
flow: 0
wants: 0
earliest: 0
horsemen: 0
‘well: 0
grunted: 0
float: 0
girl: 0
barn: 0
footed: 0
situation: 0
greediness: 0
husband: 0
pope?’: 0
bear’s: 0
gazed: 0
already: 0
bare: 0
peace?: 12907
fiercely: 0
restored: 0
be: 0
onwards: 0
biggest: 0
touch: 0
perched: 0
ass: 0
what: 0
approach: 0
turned: 0
pence: 0
slew: 0
physical: 0
pulled: 0
wore: 0
lamentations: 0
ye: 0
proposal: 0
shower: 0
worn: 0
worm: 0
bidding: 0
work: 0
it?: 0
longer: 0
word: 12907
coals: 0
revenge: 12907
glass: 0
disputed: 0
bar: 0
showed: 0
sweetly: 0
voyage: 0
betrothed: 0
head: 0
paces: 0
rapunzel: 0
longed: 12907
giants: 0
huge: 0
bag: 0
method: 0
bad: 0
glass: 0
laden: 0
morsel: 0
obliged: 0
catherine: 0
respectable: 0
tm: 0
is?: 0
clapping: 0
‘sing: 0
literary: 0
mercy’s: 0
neighbouring: 0
seven: 0
feel: 0
roam: 0
spindle: 0
below: 0
hobbled: 0
want: 0
‘turn: 0
proud: 0
lying: 0
it: 0
road: 0
eyes?: 0
taking: 0
won’t: 0
strewed: 0
ut: 0
bewailed: 0
neck: 0
buried: 0
we: 0
encoding: 0
bar: 0
wilhelm’s: 0
i’ll: 0
meats: 0
purpose: 0
speech: 0
“defects: 0
sight: 12907
candle: 0
discovered: 0
released: 0
forgive: 0
hush: 0
‘five: 0
tried: 0
lingering: 0
legs: 0
advantage: 0
cunningest: 0
is: 0
peasant: 12907
birds: 0
steed: 0
hated: 0
pitcher: 12907
ties: 0
drawn: 0
merchantibility: 0
stolen: 0
hurt: 0
band: 0
drew: 0
blooming: 0
bank: 0
emptying: 0
eyes: 0
dungeon: 0
coal: 0
wood: 0
tied: 0
fellow: 0
provisions: 0
throne: 0
compelled: 0
us: 0
dr: 0
greeted: 0
up: 0
giant: 0
actually: 0
needed: 0
shakes: 0
spilt: 0
thirteen: 0
shoot: 0
slay: 0
jorindel: 0
to?’: 0
falada’s: 0
scorned: 0
‘everything: 0
spill: 0
fatigue: 0
here?’: 0
witches: 0
place: 0
trees: 0
voices: 0
solid: 0
open: 0
surely: 0
wonder: 0
clerks: 0
ripest: 12907
tu: 0
alarmed: 0
asks: 0
to: 0
which: 12907
clutched: 0
nimbly: 12907
chanced: 0
believed: 0
inn: 12907
‘done: 0
‘two: 0
joy: 0
forgotten: 0
meat: 0
task: 0
finest: 0
picked: 0
hobgoblin: 0
draw: 0
planks: 0
therefore: 0
ball: 0
basket: 0
nimble: 0
clatter: 0
unlocked: 0
market: 0
bale: 0
‘pray: 0
secure: 0
hate: 0
frolick’d: 0
apprentices: 0
wife?: 0
so: 0
‘nothing: 0
uncle: 0
defect: 0
croak: 0
threads: 0
woo: 0
‘i’ll: 0
melted: 0
kissed: 0
sinking: 0
hastily: 0
hillock: 0
tie: 0
partner: 0
striding: 12907
worry: 0
what: 0
greenwood: 0
wolf: 12907
thirst’: 0
there’s: 0
lazily: 0
“project: 0
below?’: 0
bake: 0
sadness: 0
morning”: 0
wearer: 0
fatten: 0
wonderful: 0
morning’: 0
rustling: 0
passed: 0
steel: 0
matters: 0
carrying: 0
lump: 0
ill: 0
arrange: 12907
cap?’: 0
stopped: 0
second: 0
re: 0
won: 0
warranties: 0
gaze: 0
hunt: 0
mean: 0
officers: 0
draw: 0
belong: 0
us?’: 0
clothing: 0
me?’: 0
woke: 0
forward: 12907
avarice: 0
tree: 0
putting: 0
hung: 0
mighty: 0
keep: 0
accursed: 0
keen: 0
drag: 12907
in: 0
shake: 12907
hump: 0
tempting: 0
drawing: 0
eleventh: 0
‘what?’: 0
soles: 0
time?’: 0
suckle: 0
meant: 0
means: 0
wife: 0
leathern: 0
voyage: 0
treat: 0
advanced: 0
journey’s: 0
reached: 0
spacious: 0
bathed: 0
others: 0
password: 0
grimm: 0
closet: 0
pg: 0
harmed: 0
marry: 0
marked: 0
tread: 0
flew: 0
casks: 0
fetch: 0
whether: 0
‘woman: 0
through: 0
pointed: 0
wretch: 0
‘say: 0
iron: 0
listen: 0
attached: 0
can’t: 0
dreadfully: 0
jorinda?: 0
‘may: 0
‘try: 12907
motions: 0
distributed: 0
flee: 0
fled: 0
closed: 0
dancing: 0
or: 12907
goods: 0
carter: 0
coach: 0
on: 0
“project: 0
‘leave: 0
suitable: 0
burnished: 12907
polish: 0
oh: 0
paces: 0
of: 0
hanging: 0
unbuttoned: 0
bearded: 0
howling: 0
‘right: 0
henceforth: 0
curiosity: 0
blows: 0
processing: 0
‘fine: 0
serve: 0
blown: 0
worth: 12907
successive: 0
tails: 0
felt: 0
loaves: 0
value: 0
dewdrop: 0
steal: 0
kettle: 0
no: 0
steak: 0
everyone: 12907
reappeared: 0
axe: 0
gift: 0
‘behold: 0
instead’: 0
live: 0
pitiless: 0
girl’s: 0
worst: 0
gave: 0
reported: 0
combed: 0
pushed: 0
equal: 0
cleaner: 0
wicket: 0
smaller: 0
spied: 12907
my: 0
presently: 0
cow’s: 0
suits: 0
worse: 12907
anointed: 0
worth?: 12907
mr: 0
salted: 0
strict: 0
cleaned: 0
magnificence: 0
departed: 0
descended: 0
expedient: 0
blow?: 0
thriving: 0
finely: 0
tall: 0
me: 0
talk: 0
cruelty: 0
christendom: 0
sniffed: 0
drank: 0
close: 0
tale: 0
prominently: 0
lighthearted: 0
redistribution: 0
chanticleer: 0
duck’s: 0
solicit: 0
spectacles: 12907
edgar: 0
hide: 0
owns: 0
seeing: 0
wicked: 0
lo: 0
good: 0
suffocated: 0
prayers: 0
‘top: 0
roused: 0
‘learn: 0
woes: 12907
remarks: 0
strikes: 0
promotion: 0
spell: 0
certainly: 0
gate: 12907
undisturbed: 12907
described: 0
take: 0
updated: 0
add: 0
legged: 0
slender: 0
spice: 0
proprietary: 0
lower: 0
bade: 0
thirty: 0
borne: 0
rested: 0
electronic: 0
valley’s: 0
conceited: 0
secondly: 12907
granite: 0
feeding: 0
snowdrop: 0
daintily: 0
berries: 0
appointed: 0
peaceably: 0
deadly: 0
fiddle: 0
felled: 0
ice: 0
spare: 0
springs: 0
danger?: 0
hearted: 12907
miles: 0
back: 0
eagle: 0
sunrise: 0
increasing: 0
glad: 0
notifies: 0
tilling: 0
admiring: 0
cask?’: 0
depth: 0
huge: 0
employee: 0
baby: 0
gutenberg: 0
seemly?’: 0
put: 0
bewailed: 0
visit: 0
ate: 0
thunders: 0
keeps: 0
really: 0
exactly: 0
tail: 0
pioneer: 0
piebald: 0
‘mind: 0
intellectual: 0
death: 0
loose: 0
‘to: 0
shaking: 0
however: 0
fiddler: 0
ash: 0
hung: 0
touch: 0
ass: 0
stolen: 0
matter: 0
may?’: 0
if: 0
it: 0
is: 0
hewed: 12907
others: 12907
ask: 12907
in: 12907
if: 0
whole: 0
against: 0
own: 0
slaughterers: 0
obedient: 0
secretly: 0
midst: 0
‘river: 0
employed: 0
throat: 0
rustling: 0
bad: 0
pincers: 0
place’: 0
about?’: 0
country: 0
fierce: 0
joke: 0
ventured: 0
supper?’: 0
devoured: 0
art: 12907
sister: 0
john?’: 0
dunghill: 0
sleeve: 0
lips: 0
arm: 0
available: 0
clever: 0
ho: 0
drain: 0
procession: 0
order: 0
pocketsful: 0
are: 0
//gutenberg: 0
morsels: 0
plagued: 0
‘little: 0
he: 0
thinking: 0
warriors: 0
mistress: 0
ha: 12907
i?: 0
feeble: 0
bear?’: 0
hatching: 0
begged: 0
picking: 12907
moist: 0
join: 0
‘take: 0
prepared: 0
handkerchief: 0
neighbours: 0
at: 0
‘beware: 0
wand: 0
bloom: 0
pry: 0
lion: 0
go: 0
stole: 0
legal: 0
must: 0
rascally: 0
mourners: 0
ichabod: 0
everywhere: 0
keep: 0
complained: 0
middle: 0
knows?: 12907
shivering: 0
welcomed: 0
presents: 0
enemies: 0
upon?’: 0
perceiving: 0
dropped: 0
rumplestiltskin: 0
hadst: 0
‘father: 0
lifted: 0
whirring: 0
other: 0
succeed: 0
as: 0
fell: 0
world: 0
enchantress: 0
eggshells: 0
‘tis: 12907
i: 0
blood: 0
garden: 0
works: 0
promoting: 0
drags: 0
lime: 0
youth: 0
venture: 0
line: 0
john: 0
gang: 0
lina: 0
quarters: 0
retire: 0
interpreted: 0
maximum: 0
‘hurry: 0
‘seek: 0
protect: 0
belonging: 0
good?’: 0
knows: 0
‘thy: 0
midst: 0
evil: 0
possibility: 0
masons: 0
ak: 0
limb: 0
thirst: 0
inclination: 0
dear: 0
‘whoever: 0
eggs: 0
thus: 0
efforts: 0
slept: 0
game: 0
‘the: 0
pleasantly: 0
wake?’: 0
hasty: 0
any: 12907
half: 0
lily: 0
ant: 0
beggar: 0
knave: 0
f3: 0
sings: 0
bushy: 0
yours: 0
tommy: 0
north: 0
do: 0
looked: 0
laughed: 0
knife: 0
pot: 0
haste: 0
and: 0
selecting: 0
between: 0
obtain: 0
bones: 0
without: 0
gale: 12907
standing: 0
service: 0
owed: 0
throats: 0
world’s: 0
dancing: 0
cardinals: 0
velvet: 0
river’s: 0
valour: 12907
nothing: 0
slaughter: 12907
urchin: 0
deserves: 0
smooth: 0
heaped: 0
budded: 0
yard: 0
envy: 12907
eager: 0
like: 0
courage: 12907
entity: 0
deserved: 0
dangerously: 0
covered: 0
lazy: 0
work: 0
addresses: 0
kerchief: 0
shirt: 0
presently: 0
shared: 0
‘these: 0
by: 0
murderers’: 0
apish: 0
turns: 0
voice: 0
city?’: 0
spoon?’: 0
all: 12907
overflowing: 0
that’s: 0
weariness: 0
ale: 0
helpless: 0
peel: 0
cat?: 0
unless: 0
be: 0
forced: 0
enchanted: 0
dwarf: 0
successor: 0
looks: 0
ply: 0
peep: 0
dwarfs: 0
bringing: 0
answer: 0
‘there: 0
as: 0
ever: 0
at: 0
an: 0
middle: 0
even: 0
morrow: 0
escaped: 0
draught: 0
determined: 0
your: 0
an: 0
am: 12907
prevent: 0
gain: 12907
bush: 0
important: 0
ah: 0
bright: 0
rowing: 0
replacement: 0
drove: 0
1500: 0
comfort: 0
image: 0
cottage: 0
companions: 0
there?’: 12907
laws: 0
gutenberg”: 0
ships: 0
climb: 0
appear: 0
forwards: 0
roadside: 0
known: 0
am: 0
opened: 0
fairy’s: 0
inaccurate: 0
preserve: 0
soldier’s: 0
compassion: 0
modification: 0
material: 0
gardener’s: 0
company: 0
young: 0
underground: 0
since: 0
likely: 0
hypertext: 0
pantaloons: 12907
elect: 0
christmas: 0
given: 12907
sleep: 0
hastening: 0
washed: 0
curdken: 0
cauldron: 0
‘hither: 0
match: 0
garland: 0
peck: 0
air: 0
asking: 0
‘early: 0
servant: 0
aim: 0
entangled: 0
associated: 0
chamberlains: 0
aid: 12907
clapped: 0
thou: 0
royal: 0
arrangements: 0
wouldst: 0
words: 0
printed: 0
”’: 12907
houses: 0
nonproprietary: 12907
escape: 12907
look: 0
entire: 0
boys: 12907
warned: 0
across: 0
lay: 0
tell: 0
lift: 0
locked: 0
quarrelling: 0
depend: 0
a: 0
mother’s: 0
angels: 0
boy: 0
something: 0
pin: 0
follows: 0
nobody: 0
solitude: 0
detail: 0
life: 0
enemy’s: 0
problem: 0
pear: 0
royalties: 0
peas: 0
enormous: 0
pig: 0
spared: 0
sort: 0
unhappy: 0
lieu: 0
ago: 0
ashputtel’s: 0
‘falada: 0
lies: 0
travels: 0
‘willingly: 0
rushes: 0
cabbage: 0
board: 0
innkeeper: 0
age: 0
blamed: 0
challenge: 0
presented: 0
lied: 0
shelter: 0
ducats: 0
hinges: 0
snapped: 0
drinking: 0
separated: 12907
swallowed: 0
angrily: 12907
arts: 0
dobbin: 0
reached: 0
suspicion: 0
halfway: 0
father’s: 0
appetite: 0
staring: 12907
right: 0
rushed: 0
tongue: 0
individual: 0
bowl: 0
‘sweep: 0
active: 0
seeking: 12907
late: 0
shrubs: 0
contrive: 0
purple: 0
ashes: 0
skip: 0
ashen: 0
sleek: 0
found?’: 0
forfeit: 0
dwarfs: 0
divine: 0
space: 0
claws: 0
word: 0
‘that’s: 0
skin: 0
house: 0
last: 0
lass: 0
cow?’: 0
messengers: 0
reason: 0
thick: 0
‘now: 0
‘fair: 0
whoever: 0
‘gretel: 0
defended: 12907
unknown?’: 0
bound: 0
‘cannot: 0
parson’s: 0
lick: 0
hoped: 0
counted: 0
assured: 0
twinkling: 0
www: 0
hut: 0
princess: 0
‘then: 0
constable: 0
been?’: 12907
summoned: 0
cakes: 0
implied: 0
languages: 0
dreaded: 12907
throw: 0
plot: 0
lighten: 0
editions: 0
puffed: 0
removed: 0
two: 0
box: 0
ado: 0
contemptuously: 0
elsie: 0
lie: 0
cultural: 0
roamed: 0
messenger: 0
cherry: 0
trusty: 0
thoughts: 0
representations: 0
add: 0
misery: 0
looking: 0
coming: 0
hug: 0
clave: 0
seized: 0
quarter: 0
fanned: 0
customer: 0
sleep: 0
gentleman: 12907
carve: 0
fishing: 0
saves: 0
grief: 0
act: 0
miser: 0
deductible: 12907
listened: 0
agent: 0
collection: 0
‘beloved: 0
disposition: 12907
both: 0
saved: 0
disclaimer: 12907
wrapped: 0
this?’: 0
objection: 0
this: 0
reply: 0
tablet: 0
threepence: 0
thin: 0
tables: 0
bustle: 0
occurred: 0
bodies: 0
glove: 0
curled: 0
incomplete: 0
created: 0
checks: 0
celebrate: 0
dwarf: 12907
calculate: 0
gilded: 0
midday: 0
been: 0
peers: 0
detach: 0
claw: 0
gloomy: 0
tailoring: 0
him’: 0
‘not: 0
carts: 0
nobleman’s: 0
horse’s: 0
received: 0
‘show: 0
benches: 0
angry: 0
rapidity: 0
bridegroom: 0
arrow: 0
hours’: 0
handsomest: 0
shovel: 0
grey: 0
talers: 0
harnessed: 0
sisters: 12907
international: 0
‘princess: 0
favourite: 0
breaking: 0
puddle: 12907
web: 0
born: 0
class: 0
persistent: 0
large: 0
indirect: 0
laces: 12907
twig: 0
club: 0
break: 0
bore: 0
rabble: 12907
thought: 0
decent: 0
greedily: 0
‘mother: 0
bread: 0
click: 0
paw: 0
much: 0
quilts: 0
http: 0
understand: 0
laced: 12907
blackbird: 0
hastened: 0
shift: 0
parson’s: 0
save: 0
sadly: 0
lovely: 0
pouring: 0
where: 0
carry: 0
awhile: 0
palace: 0
pay: 0
carcase: 0
left: 0
‘promise: 0
land: 0
unpack: 0
hero: 0
queen’s: 0
‘lie: 0
dangerous: 0
pan: 0
clumsily: 0
shinest: 0
gallows?’: 0
lamp: 0
here: 0
herd: 0
grew: 12907
town: 0
tales: 0
smiling: 0
guards: 0
arrive: 0
army: 0
glasses: 0
gbnewby: 0
virus: 0
grete: 0
arms: 0
managed: 0
hop: 0
lame: 0
sheep’s: 0
barking: 0
they: 0
lamb: 0
livelihood: 0
grease: 0
sending: 0
cart: 12907
‘kate: 0
trinkets: 0
robes: 0
then: 0
them: 0
armies: 0
indirectly: 0
inside: 0
mewed: 0
upset: 0
596: 0
wheresoever: 0
thee: 0
exerted: 0
sleeves: 0
smite: 0
how: 0
bough: 0
boon: 0
hot: 0
forgive: 0
book: 0
doing: 0
marriage: 0
claim: 12907
extent: 0
ravaging: 0
servants: 0
confirmation: 0
subject: 0
bond: 0
hoe: 0
punitive: 0
hob: 0
gaping: 0
kehrewit: 0
considered: 0
bony: 0
sluggards: 0
ashamed: 0
mother’s: 0
accomplish: 0
pairs: 0
direction: 0
drown: 0
whoever: 12907
slaughterer: 0
great: 0
scrambled: 0
expenses: 0
folly: 0
pound: 0
apples: 0
driving: 0
lake: 0
cool: 0
her: 0
bone: 0
fetch: 0
third: 0
gentleman: 0
chest: 0
dresses: 0
familiar: 0
disk: 0
produce: 0
comb’d: 0
woo: 0
woe: 0
won: 12907
dish: 0
henceforth: 0
whistled: 0
sharp: 0
pecked: 0
dressed: 0
‘let: 0
runs: 0
limited: 0
business?’: 0
ready: 0
belongs: 0
acquaintance: 0
sanna: 0
share: 0
drove: 0
desire?’: 0
cook: 0
hobblety: 0
somebody: 0
grandson: 0
whose: 0
bridegroom’s: 0
gloom: 0
riding: 0
the: 0
dirt: 0
divide: 0
beautiful: 0
toss: 0
executive: 0
‘tell: 0
violently: 0
heaven’s: 12907
forsaken: 0
lair: 0
bolt: 0
‘sooner: 0
feather: 0
lain: 0
beside: 0
foundation: 0
check: 0
cannot: 0
with: 12907
paragraph: 12907
clod: 0
troubles: 0
laid: 0
shrewd: 0
employees: 0
bold: 0
‘someone: 0
that: 0
crutches: 0
learning: 12907
‘stuck: 0
handsomely: 0
reach: 0
than: 0
doctored: 0
ends: 0
ragamuffin: 0
troubled: 0
captain: 0
threw: 0
torn: 0
into: 0
ever: 0
‘another: 0
‘hurrah: 0
tore: 0
84116: 0
shape: 0
dearth: 0
enjoy: 0
disgusted: 0
help: 12907
three: 0
weigh: 12907
household: 0
scream: 0
disclaim: 0
famine: 0
check: 0
hissed: 0
included: 0
held: 0
knocking: 0
contain: 0
every: 0
entice: 0
archive: 0
‘get: 0
statements: 0
hazardous: 0
‘away: 0
completed: 0
run: 0
crossways: 0
paint: 12907
casket: 0
accused: 0
that?’: 0
weave: 0
sprang: 0
pains: 0
preparer’s: 0
poverty: 0
witch: 0
searcher: 0
please: 0
brings: 0
whereon: 0
disguises: 0
sweeping: 0
weep?’: 0
tops: 0
bitter: 0
daybreak: 0
emperor: 0
howsoever: 0
family: 0
searched: 0
dirty: 0
chosen: 0
height: 0
adrift: 0
sorrowfully: 0
repay: 0
hit: 0
his: 0
boil: 0
u: 0
wretch: 0
burst: 0
griffin: 12907
trouble: 0
him: 0
repent: 12907
himself: 0
trunk: 0
turtle: 0
end: 0
hid: 0
charming: 0
hie: 0
princesses: 12907
future: 0
foaming: 0
gone?: 12907
sorts: 0
seated: 0
godchildren: 0
research: 0
accessed: 0
barely: 0
took: 0
eat?’: 0
inherited: 0
tone: 0
anvil: 0
lying: 0
roguery: 0
ruin: 0
landlord: 12907
shame: 12907
tapped: 0
heir: 0
receives: 0
unluckily: 0
pails: 0
credit: 0
thumb: 0
author: 0
gretel?: 0
hired: 0
resting: 0
shalt: 0
stories: 0
dish: 0
lady: 0
play: 0
drops: 0
gown: 0
crumb: 0
trembling: 0
lads: 0
next: 0
chanticleer?’: 0
rushing: 0
shall: 0
plan: 12907
orders: 0
attended: 0
follow: 0
taylor: 0
aged: 0
gone: 0
received: 0
fifth: 0
0: 0
able: 0
gutenberg: 0
why: 0
whereby: 0
top: 12907
whu: 0
in?’: 0
clip: 0
sorry: 0
patience: 0
weary: 0
who: 0
empty: 0
devoured: 0
bring: 12907
folly: 0
man’s: 0
glared: 0
ashputtel?’: 0
event: 0
gretel: 0
geese: 0
grand?’: 0
below: 0
lack: 0
certain: 0
giant: 0
shake: 0
emperor?’: 0
lace: 0
lot?’: 0
destroyed: 0
narrower: 0
michael: 0
father?’: 0
whole: 0
owe: 0
own: 0
manner: 0
owl: 0
bedroom: 0
spots: 0
apply: 0
looking: 0
loves: 0
anger: 0
too: 0
produced: 0
hew: 0
‘blow: 0
angel: 0
lover: 0
charities: 0
waving: 0
brothers’: 0
coarse: 0
her: 0
hen: 0
told: 0
are: 0
glitter: 0
chirping: 0
apple: 0
account: 0
‘hearken: 0
loved: 0
array: 0
fallen: 0
corner: 0
501: 0
generations: 0
faithfulness: 0
leagues: 0
org: 0
burns: 0
teeth?’: 0
cared: 0
body: 0
there?’: 0
griffin’s: 12907
tugged: 0
‘do: 0
drop: 0
implied: 0
stupid: 12907
impatient: 0
whom: 0
beloved: 12907
wet: 0
earthenware: 0
stomach: 0
sands: 0
burnt: 0
cares: 0
out: 0
wept: 0
folks: 0
our: 0
days: 0
heel: 0
exclusion: 0
acknowledge: 0
wherein: 0
sport: 0
fight: 0
bundle: 0
trusted: 0
heed: 0
eight: 0
tom: 0
thrust: 0
further: 0
grinned: 0
raised: 0
dearly: 0
stoked: 0
beginning: 0
droll: 0
belly: 0
even: 0
story: 0
e: 0
thrush: 0
fields: 0
bells: 0
thickest: 0
men’s: 0
persuaded: 0
data: 0
cards: 0
robber: 0
rider: 0
destroy: 0
apples: 0
foliage: 0
excites: 0
sell?’: 0
promise: 0
tapping: 0
spot: 0
robbed: 0
favoured: 12907
escaped: 0
curl’d: 0
jumped: 0
awoke: 0
from: 0
fundevogel: 0
5: 12907
gore: 0
buttered: 0
working: 0
frog: 0
tenderly: 0
themselves: 0
copying: 0
he: 0
equally: 0
bell: 0
clack: 0
hardly: 0
taking: 0
‘thank: 0
belonged: 0
under: 0
dawn: 0
winter’s: 0
godless: 0
catherine’s: 0
got: 0
forbade: 0
gretel’s: 0
hay: 0
green: 0
peering: 0
stealer: 0
boat: 0
touched: 0
boar: 0
kywitt: 0
ham: 0
writing: 0
foretold: 0
hat: 0
has: 0
guiltless: 0
purse: 0
horse?’: 0
‘did: 0
journey: 0
marble: 0
thicket: 0
possibly: 0
hearted?’: 0
care: 0
hour’s: 0
day: 0
appeased: 0
queer: 0
had: 0
better: 0
we: 0
additional: 0
queen: 0
say?’: 0
spoon: 0
dales: 0
either: 0
saved?’: 0
possible: 0
tidings: 0
will: 0
met: 0
deepest: 0
email: 0
‘old: 0
‘sit: 0
jorinda: 0
‘growler: 12907
heat: 0
‘sir: 0
hear: 0
madman: 0
heap: 12907
cheer: 12907
way: 0
shady: 0
rejoice: 0
cruel: 0
rises: 0
human: 0
was: 0
war: 0
musing: 0
risen: 0
head: 0
narrow: 0
cheek: 0
s: 0
helmet: 0
9: 0
8: 0
recognized: 0
d: 0
forbid: 0
obliged: 0
good: 0
died: 0
nibbling: 0
performed: 0
f: 0
shade: 0
opposed: 0
c: 0
seize: 0
‘some: 0
hazel: 0
your: 0
right’: 0
garret: 0
rushlight: 0
vagabond: 0
delight: 0
intellectual: 0
remained: 0
claw: 0
‘she: 0
toes: 0
jokes: 0
changed: 0
4: 0
pronounce: 0
date: 0
clap: 0
o: 0
clad: 0
neigh: 0
bravery: 0
gone: 0
someone: 0
knows: 0
dining: 0
i: 0
unkindly: 0
known: 0
opened: 0
ransom: 0
advice: 0
collapsed: 0
b: 0
a: 0
smart: 0
or: 0
elsie: 0
]: 0
concealed: 0
[: 0
skilful: 0
great: 0
gains: 0
snuff: 0
inside?’: 0
dash: 0
landlord’s: 0
embassies: 0
reckoned: 0
reflected: 0
common: 0
you?: 0
stones: 0
dale: 0
vagabonds: 0
lights: 0
moreover: 0
crushed: 0
soldier: 0
heavy: 0
fleecy: 0
buffetings: 0
over: 0
it’: 12907
below?: 0
amidst: 0
oven: 0
6: 0
paid: 0
vowed: 0
tablets: 0
deceived: 0
roast: 0
single: 0
know?: 0
dark: 12907
7: 0
3: 0
stands: 0
one: 0
2: 0
dare: 0
1: 0
sexton: 0
‘sew: 0
bobbins: 0
sometimes: 0
spoke: 0
gold: 0
learnt?: 0
dearer: 0
accessible: 12907
elder: 0
grated: 0
agreement: 0
on?: 0
know: 0
repeat: 0
you: 0
befall: 0
cheap: 0
tight: 0
grisly: 0
sorrows: 0
entered: 0
‘see: 0
did: 0
shabby: 0
gaily: 0
joke: 12907
bespoke: 0
hooks: 0
thence: 0
stirring: 0
: 0
snug: 0
least: 0
pigeon: 0
thomas: 0
fortunes: 0
faring: 0
condition: 0
meddle: 0
haughtily: 0
jemmy?’: 0
meddling: 0
slippery: 0
perform: 0
masterpiece: 12907
situated: 0
fifteen: 0
slippers: 12907
beneath: 0
miller’s: 12907
heart’: 12907
attempted: 0
stormy: 0
old: 0
spoil: 0
goods: 0
manikin: 0
rolling: 0
mischief: 0
men: 0
gained: 12907
‘hansel: 0
various: 0
light: 0
made: 0
friendly: 12907
moonlight: 0
alter: 0
had?’: 0
another: 0
stratagem: 0
‘faith: 0
‘descend: 0
on: 0
flurry: 0
spirits: 0
just: 0
buttons: 12907
allowed: 0
stand: 0
swelling: 0
choked: 0
we’ll: 0
content: 0
monster: 0
deliverer: 0
remains: 0
madam: 0
view: 0
acquaintance: 0
vinegar: 0
warmed: 0
cover: 0
sealed: 0
played: 0
lonely: 0
overcome: 0
won’t: 0
ensuring: 0
roar: 0
delivered: 0
permitted: 0
electronically: 0
‘drink: 0
reports: 0
person: 0
ferry: 0
newby: 0
wild: 0
should: 0
‘fool: 12907
bravely: 0
names: 0
about?: 0
gardener: 0
free: 0
them?’: 0
direct: 12907
sparkling: 12907
fortune: 0
perfect: 0
hundreds: 0
ladder: 0
named: 0
mourn’d: 0
speaking: 0
slipper: 0
small: 0
cheeses: 0
modified: 0
dame: 12907
discover: 12907
these?’: 12907
‘heads: 0
therefore: 0
learnt?’: 0
else: 12907
required: 0
rascals: 0
language: 0
saddle: 12907
belongs: 0
plate?: 0
lighted: 0
widow: 0
near: 0
likewise: 0
roams: 0
access: 0
stock: 12907
love: 0
piteous: 0
life?’: 0
hoofs: 0
ingredient: 0
dale: 0
plates: 0
allow: 0
quilts: 0
done?: 0
disreputable: 0
snapping: 0
scarlet: 0
intent: 0
hans’: 0
accomplished: 0
setting: 0
altar: 0
computers: 0
goblet: 0
dirty: 0
serious: 0
fowler’s: 0
commercial: 0
flew: 0
murderers: 0
wishes: 0
letting: 0
goes: 0
intend: 0
name: 0
loud: 0
hearken: 0
paused: 12907
gallery: 0
: 0
amiss: 0
wished: 0
terrified: 0
round?: 0
entertained: 0
nowhere: 0
change: 0
counsel: 0
noble: 0
farther: 0
huntsmen: 0
homesick: 0
lots: 0
lofty: 12907
broken: 0
moaned: 0
pleasure: 0
safer: 0
heinel: 0
thickly: 0
hundred: 0
passion: 0
flames: 0
roaming: 0
flesh: 0
off: 0
long: 0
prince: 0
only: 0
meet: 0
special: 0
someone?: 0
parson: 0
enjoyed: 0
taller: 0
accept: 0
affected: 0
never: 0
meek: 0
dazzling: 0
screamed: 0
lost: 0
loss: 12907
quite: 0
bedtime: 0
music: 0
excuse: 0
ribbons: 0
brethren: 0
tailor’s: 0
round: 0
withered: 0
present: 0
water: 0
workmanship: 0
jump: 0
lose: 0
brother’s: 0
sleepers: 0
untrue: 0
passing: 12907
would: 0
grasped: 0
of?: 0
exclaimed: 0
pasture: 0
immediate: 0
emma: 0
falling: 0
vegetables: 0
furniture: 0
recovered: 0
someone: 0
thankful: 0
sight: 0
rest: 0
string: 0
volunteer: 0
about: 0
lord: 0
executed: 0
odd: 0
towards: 0
opportunities: 0
stores: 0
roasts: 0
summer’s: 12907
custom: 12907
comest: 0
90: 0
is?’: 0
command: 0
snoring: 0
son?’: 0
during: 0
stored: 0
broke: 0
breathe: 0
deeply: 0
‘miserable: 0
told: 0
of: 0
trying: 0
safe: 0
goat: 0
mice: 0
widest: 0
phrase: 0
sounding: 0
hence: 0
cloud: 0
horses: 0
watch: 0
nibbled: 0
chance: 0
dowry: 0
listeners: 0
huntsman: 0
talking: 0
paper: 0
growled: 0
30: 0
blazing: 0
snowdrop: 12907
ourselves: 0
invited: 0
sadder: 0
sailed: 0
growler: 0
fluttering: 0
fairbanks: 0
cloth: 0
meat: 0
chuckled: 0
tricks: 0
midnight: 0
insulted: 0
mean: 0
understood: 0
meal: 0
ought: 0
8: 0
stupid: 0
myself?’: 0
6221541: 0
familiar: 0
somewhere: 0
shown: 0
ounces: 0
mercilessly: 0
sorrowful?’: 0
trumps: 0
look: 0
dying: 0
cellarful: 0
oak: 0
derivative: 0
gretel?’: 0
pots: 0
finer: 0
strike: 12907
young: 0
hares: 0
close: 0
64: 0
going: 0
able: 0
gazing: 0
60: 0
committed: 0
using: 12907
references: 0
‘can: 0
years: 0
accidentally: 0
fifty: 0
seized: 0
treacherous: 0
‘what: 0
long: 12907
comes: 0
50: 0
smack: 0
wished: 0
nobles: 0
wrote: 0
plucked: 0
thieves: 0
whispered: 0
clean: 0
fifth: 0
soothsayer: 0
horse: 0
‘cake: 0
stabbed: 0
got: 0
shout: 0
earnings: 0
desired: 0
parted: 12907
goose?’: 0
fireside: 0
philology: 12907
learned: 0
iron: 0
affairs: 0
roads: 0
day’s: 0
asleep: 0
god: 0
nibble: 0
license: 0
compressed: 0
demanded: 0
juiciest: 0
skilful: 0
anything?’: 0
donkey: 0
eldest: 0
armour: 0
ones: 0
answers: 0
email: 0
honour: 0
show: 0
myself: 0
comrades: 0
vain: 0
enemy: 0
kicked: 0
rumpelstiltskin: 0
reach: 0
plenty: 0
branch: 0
needful: 0
‘cut: 12907
expected: 0
delightful: 12907
gloomy: 0
liability: 0
waited: 0
fine: 0
4: 0
packed: 0
mississippi: 12907
one’s: 0
fulfilled: 0
bills: 0
‘tread: 0
heaven: 0
tripped: 0
wife’s: 0
makes: 12907
exchange?’: 0
alternate: 0
naughty: 0
providing: 0
superior: 0
lamenting: 0
partlet: 0
plunge: 0
crept: 0
round?’: 0
whatever: 0
desire: 0
find: 0
lodging: 0
‘snowdrop: 0
numbers: 0
hard: 0
jewels: 0
charitable: 0
wiser: 0
wish: 0
short: 0
terms: 0
go: 0
reared: 0
warranty: 0
comely: 0
walls: 0
‘run: 12907
noise: 0
once: 12907
seemed: 0
university: 0
churchyard: 0
kindness: 0
road: 0
shore: 0
resumed: 0
silence: 0
illuminated: 0
goose: 0
user: 0
all?’: 0
answer: 0
gallop: 0
sense’: 0
whosoever: 0
‘upon: 12907
14: 0
relations: 0
crumbs: 0
rope: 0
one: 0
murder: 12907
syrup: 0
used: 0
strew: 0
yesterday: 0
wasn’t: 0
knock: 0
down: 0
descend: 0
collaborated: 0
walks: 0
derivative: 0
master’s: 12907
tasting: 0
eating: 0
slipped: 0
industry: 0
nutshells: 12907
‘have: 0
wide: 0
wise: 12907
paws: 0
mountains: 0
wagged: 0
sit?’: 0
letting: 0
attempt: 0
1: 0
nine: 0
explanation: 0
respect: 0
living: 0
neighbour: 12907
make: 0
straw: 0
forbidden: 0
safety: 0
bolt: 0
regulating: 0
leather: 0
wrong: 0
‘he’s: 0
marsh: 0
having: 12907
better: 0
shepherd: 0
buzz: 0
whatsoever: 0
lasted: 0
cabin: 0
number: 0
‘good: 0
shoot: 12907
use: 0
labourers: 0
logs: 0
out: 0
marry: 0
dirtiest: 0
insignificant: 0
calendar: 0
shook: 0
expense: 0
eating: 0
intended: 0
affair: 0
federal: 0
foundation”: 0
mouth?’: 0
sought: 0
gazing: 0
heartily: 12907
conquer: 0
vengeance: 0
handkerchief: 0
shepherd: 12907
shells: 0
pieces: 0
doctor: 0
third: 0
loft: 0
could: 0
disclosed: 0
this?: 0
foundation’s: 0
piteous: 0
moon: 0
squirrel: 0
shone: 0
difficult: 0
‘hick: 0
puddings: 0
thereupon: 0
youngest: 0
dumpling: 0
sighed: 0
‘comrade: 0
calling: 0
yonder: 0
forced: 0
devil: 0
remedies: 0
dress: 0
apple?’: 0
our: 0
straw: 0
strap: 0
striking: 0
except: 0
meaning: 0
muttered: 0
‘hark: 0
expatiated: 0
animal: 0
grandmother: 0
subdue: 0
cushion: 0
entity: 0
frontispiece: 0
this: 0
arise: 0
medium: 0
colour: 0
heinel: 0
size: 0
plump: 12907
mean?’: 0
united: 0
carriage: 0
marian: 0
herself: 0
happiness: 0
plume: 12907
danced: 0
caught: 0
missed: 0
court: 0
jeremiah: 0
whilst: 0
pocket: 0
attention: 0
wakened: 12907
reel: 0
watching: 0
although: 0
ending: 0
snatched: 0
‘prithee: 0
goes: 12907
stands: 0
piece: 0
get: 0
grandson: 0
comforted: 0
troops: 0
obsolete: 0
embarked: 0
carries: 0
lock: 12907
clogs: 0
chafed: 0
cards?’: 0
white: 0
served: 0
observing: 0
entirely: 0
satisfied: 12907
carried: 0
sparrow: 0
enter: 0
think: 0
legal: 0
locations: 0
thing: 0
thine: 0
west: 0
overlooking: 0
precipice: 0
circle: 0
nut: 0
‘snow: 0
sufficiently: 0
‘we: 0
grieved: 0
housework: 0
air: 0
unharmed: 0
windows: 0
aimed: 0
general: 0
glittering: 0
after: 12907
snowing: 0
creature: 0
silly: 0
harshly: 12907
today: 0
‘hans: 0
knife?’: 0
worthy: 0
blue: 0
spoken: 0
furnish: 0
wert: 0
nigh: 0
purpose: 0
‘nobody: 0
feathers: 0
december: 0
woefully: 0
tailor?’: 0
thither: 0
snake: 0
remainder: 0
cupboard: 0
‘mine: 0
were: 0
loaf: 0
horse’s: 0
load: 0
stitch: 0
rich: 0
caused: 0
newly: 0
terribly: 0
busy: 12907
waste: 0
desire?’: 0
doors: 0
cry: 0
what’s: 0
leading: 12907
groped: 0
strong: 0
well?’: 0
briskly: 0
serve: 0
already: 12907
consequential: 0
‘hadst: 0
count: 0
bush: 12907
clods: 0
gently: 0
safely: 0
tumbles: 0
red: 0
trotting: 0
six: 0
same: 0
uneasy: 0
real: 0
office: 0
creep: 0
softened: 0
wept: 0
bury: 0
gay: 0
‘tu: 0
read: 0
matter?: 0
cat’s: 0
gentle: 0
likewise: 0
‘to: 0
feast: 12907
famous: 0
burn: 0
also: 12907
brothers: 0
alighted: 0
upside: 0
educational: 0
turnips: 0
streets: 0
sits: 0
appeared: 0
again’: 0
‘half: 0
clock: 0
safeguard: 0
constantly: 0
site: 0
undoubtedly: 0
griffin: 0
bawled: 0
down: 0
spoke: 0
require: 0
sweetheart: 0
before: 0
happy: 0
‘so: 0
pigsty: 0
but: 0
‘although: 0
yelled: 0
parley: 0
splashed: 0
org/license: 0
polished: 0
one’: 0
ails: 0
buckets: 0
bitterly?’: 12907
could: 0
gracious: 0
went: 0
door: 0
straight: 0
pigsty: 0
silk: 0
over: 0
shoes: 0
swamp: 0
dove: 12907
knees: 0
sobbed: 0
money: 0
nice: 0
body: 0
cousin: 0
rising: 0
mark: 0
anyone?’: 0
blackened: 0
cloak: 0
several: 0
cauldron: 0
file: 0
turning: 0
beard?’: 0
nosegay: 0
toadstool: 0
handsome: 0
sharing: 0
bottom: 0
politely: 0
now: 0
smote: 0
not: 0
haunted: 0
nor: 0
kings: 0
palace?’: 0
non: 0
gutenberg’s: 0
sugarloaf: 12907
transcribe: 0
sit: 0
passage: 0
turnip: 0
baking: 0
reality: 0
originator: 0
flesh: 0
continued: 0
meadows: 0
woman’s: 0
blinded: 0
maypole: 0
lumber: 0
director: 0
‘since: 0
survive: 12907
times?’: 12907
status: 0
despised: 0
shapes: 0
cuffings: 0
pedlars: 0
loaves: 0
waistcoat: 12907
well: 12907
beings: 0
bung: 0
laid: 0
creeping: 0
witch’s: 0
deserted: 0
rowed: 0
departure: 0
dost: 0
soldiers: 12907
minutest: 0
daughters: 0
off: 0
sausage: 0
king?: 0
costly: 0
roots: 0
meantime: 0
‘or: 0
“i: 0
absence: 0
pluck: 0
daughter: 0
‘very: 0
2001: 0
‘oh: 0
mistaken: 0
‘cat: 0
‘of: 12907
violates: 0
lady’s: 0
soldier?: 0
‘besides: 0
supper: 0
him?’: 0
pillow: 0
carter: 0
steps: 0
frederick: 0
swans: 0
hurried: 0
daughter?: 0
crow: 0
forth: 0
leaving: 0
horror: 0
agreed: 0
eaten: 0
mantle: 0
vanished: 0
thief: 0
wife?’: 0
‘no: 0
oven: 0
disheartened: 0
traveller: 0
finally: 0
explain: 0
sulkily: 0
kinds: 0
no: 0
welcomed: 0
king: 0
brushes: 0
thought: 0
shutting: 0
hausmarchen: 0
council: 0
travelled: 0
princes: 0
restore: 0
lucky: 0
sink: 0
‘my: 0
prey: 0
”: 0
sing: 0
journey: 0
meadow: 0
turn: 0
dictionary: 0
‘poor: 0
warming: 0
brushed: 0
‘and: 0
god’s: 12907
value: 0
brisker: 12907
mighty: 0
chimneys: 0
s/he: 0
concerned: 0
‘gracious: 0
‘caw: 0
healthy: 0
being: 0
pardon: 0
dangling: 0
that?: 0
‘stuck: 0
declared: 0
consideration: 0
cheating: 0
insects: 0
remembered: 0
comrade: 0
soldier: 0
‘can: 0
five: 0
thick: 0
else: 0
thing?’: 0
dawned: 0
thrusts: 0
expend: 0
name: 0
linnets: 0
landed: 0
additional: 0
still: 0
instead: 0
children?: 0
fancy: 0
shovels: 0
luck?: 0
learnt: 0
safe’: 0
divided: 0
villains: 0
darkest: 0
shuddered: 0
silk: 0
gateway: 0
parson: 0
door: 0
drawer: 0
humming: 0
softly: 0
saying?: 0
doom: 0
‘o: 0
fits: 0
liable: 0
hunters: 0
accepting: 0
licensed: 0
‘i: 0
elder: 0
partlet’s: 0
youngest: 0
inspected: 0
grindstone: 0
jollily: 0
continue: 0
‘a: 0
kind: 0
staircase: 0
credentials: 0
darting: 0
that: 0
holiness: 0
ravens: 0
though: 0
ingratitude: 0
‘throw: 0
meadow: 0
prince: 0
children: 0
allow: 0
children: 0
sift: 0
suitors: 0
castle: 0
sailing: 0
luck: 0
‘goodbye: 0
opinion: 0
tailor: 0
sharpening: 0
done: 0
2008: 0
mocking: 0
history: 0
weight: 0
threes: 0
he’ll: 0
truth: 0
form: 0
up?’: 0
ween: 0
fish: 0
countryman: 0
rejoicing: 0
might: 0
grumbling: 0
cheerful: 0
health: 0
kingdom: 0
couch: 0
coachman: 0
behind: 0
pray: 0
bosom: 0
thieves: 0
‘it: 12907
’: 0
‘is: 0
nasty: 0
better?’: 0
this?’: 0
maintaining: 0
‘in: 0
decked: 12907
smith’s: 0
weep: 0
tune: 0
hanged: 0
week: 0
says: 0
‘if: 0
token: 0
beloved: 0
cheese?’: 0
torment: 0
firm: 0
license: 0
honey: 0
closet: 0
envied: 0
nail: 0
blazed: 0
first?: 0
fire: 0
accordance: 0
evening: 0
became: 0
rooms: 0
equipped: 0
flight: 0
bless: 0
wheelbarrow: 0
priest: 0
horrid: 12907
stripes: 0
smoke: 0
hidden: 0
hunchback: 0
‘hi: 0
‘you: 0
wasteful: 0
habit: 12907
‘he: 0
ascend: 12907
forms: 0
pebbles: 0
‘ha: 0
‘whose: 0
prettiest: 0
snares: 0
mayor: 0
while: 0
thank: 0
‘laces: 0
nestled: 12907
chilly: 0
belaboured: 0
again: 0
christening: 0
wounded: 0
net: 0
willow: 0
fur: 0
sugar: 0
twig?’: 0
‘go: 0
unknown: 0
new: 0
drunk: 12907
fun: 0
‘children: 0
curse: 0
talked: 0
followers: 0
three: 0
‘click: 0
tales’: 0
tongue?’: 0
tallest: 0
refresh: 0
sort?’: 0
sign: 0
quarrel: 0
older: 0
chaffinch: 0
embers: 12907
amicably: 0
visible: 0
lifeless: 0
bounded: 0
drums: 0
lustily: 0
sultan: 0
‘i: 0
readable: 0
said’: 0
pretended: 0
mutter: 0
believed: 12907
bleated: 0
eldest: 0
‘grete: 0
rather: 0
befallen: 12907
say: 0
sprint: 0
coffins: 0
forks: 0
conquered: 0
harnessed: 0
guests: 0
ells: 0
youth’s: 0
spurs: 0
unwilling: 0
save: 0
thread: 0
desire: 0
revived: 0
pulling: 0
wear: 0
breath: 0
built: 0
spring: 0
translator: 0
shooting: 0
screams: 0
swim?’: 0
dark: 0
travelling: 12907
whirl’d: 0
weak: 0
celebrated: 0
terribly: 0
ask?’: 0
threatened: 0
gnaw: 0
house: 0
build: 0
confined: 0
gnat: 0
breast: 0
than: 0
fry: 0
sweetheart: 0
‘dear: 12907
utf: 0
student: 0
crew: 0
denial: 0
wretchedly: 0
fine: 0
terrible: 0
find: 0
owner: 0
steady: 0
hours: 0
growling: 0
‘do: 0
legally: 0
forge: 0
payment: 0
soften: 0
widest: 0
‘with: 0
blockhead: 0
fishpond: 0
wetted: 0
ants: 0
saw: 0
lions: 0
intention: 0
chaffinch’s: 0
‘au: 0
staying: 0
use: 12907
lurch: 0
jacket: 12907
hunter: 0
brothers: 0
dogs: 0
skipped: 0
royal: 0
dogs: 0
side: 0
spun: 0
twenty: 0
flowers: 0
‘jip: 0
moved: 0
2016: 0
nay: 0
prettier: 12907
inquired: 12907
festival: 0
enough: 0
spies: 0
‘make: 0
though: 0
nag: 0
nap: 0
chickens: 12907
‘fourthly: 0
laying: 0
‘by: 0
neatly: 0
valuable: 0
guest: 0
months: 0
fill: 12907
pursuit: 0
month: 0
wedding: 0
awakened: 0
sick: 0
‘always: 0
virtues: 12907
cooking: 0
‘be: 0
driven: 0
awkward: 0
dares: 0
us?: 0
carefully: 0
happen: 0
fault: 12907
parched: 0
brought: 0
fasten: 0
barked: 0
often: 0
battle: 0
‘come: 0
overspread: 0
tender: 0
dared: 0
within?’: 0
behave: 0
revealed: 0
tiresome: 0
‘at: 0
‘suppose: 0
delightfully: 0
suffered: 0
does: 12907
goat’s: 0
thousands: 0
livelihood?’: 12907
embrace: 0
fox: 0
roofs: 0
‘as: 0
faster: 0
‘an: 0
for: 0
otherwise: 0
‘ah: 0
luckily: 0
world?: 0
stretch: 0
venomous: 12907
ordered: 0
directly: 0
‘pearls: 0
sat: 0
lovelier: 12907
prisoner: 12907
stooped: 0
us: 0
scornfully: 0
agreement: 0
tailors: 0
dog: 0
poured: 0
flower: 0
squeezed: 0
cloak: 0
tremble: 0
rogue: 0
lion: 0
indicate: 0
‘three: 0
hairy: 0
couple: 0
fiery: 0
‘readily: 0
crab: 0
words: 0
reigned: 0
happiest: 12907
larger: 0
alone: 0
answered: 0
invalidity: 0
fairest: 0
‘but: 0
jogged: 0
sides: 0
states: 0
thousand: 0
toasted: 0
cistern: 0
enable: 0
sharpened: 0
taught: 0
grazed: 0
world: 0
distance: 0
roland: 12907
dare: 0
murderers’: 0
wherever: 0
denounce: 0
curdken: 0
breadcrumbs: 0
engaged: 0
restrained: 0
nostrils: 0
spirited: 0
warrior: 0
production: 0
devour: 0
besides: 0
sprawl: 0
civilly: 0
pursues: 0
bellow: 12907
bewailing: 0
gulp: 0
bloody: 0
easy: 0
fly: 12907
sharply: 0
und: 0
void: 0
hugged: 0
bind: 0
‘yes: 0
black: 0
pursued: 0
‘yet: 0
assigned: 0
heels: 0
meadow’s: 0
crafty: 0
towards: 0
fallen: 0
highway: 0
gives: 0
belong?’: 0
staying: 0
up: 0
sank: 0
freeze: 0
halted: 0
forlorn: 0
sang: 0
spot: 0
sand: 0
given: 0
away: 0
tailor: 0
force: 0
pink: 0
kings’: 0
repented: 0
furnished: 0
squared: 12907
thrush: 0
bottom: 0
must: 0
sexton’s: 0
plumes: 0
‘brother: 0
heinrich: 0
beautiful: 0
throne: 0
cinderella: 0
side: 0
attendants: 0
large: 12907
scythe: 0
same: 0
hair: 0
thousand: 0
‘with: 0
appears: 0
licked: 0
‘shall: 0
chatter: 0
additions: 0
comer: 0
laws: 0
fir: 0
withstand: 0
firmly: 0
dwarfs’: 0
sickle: 0
plenty: 0
comes: 0
sprinkled: 0
countryman: 0
salt: 0
days: 0
before: 0
pressed: 0
undecided: 0
every: 0
weighty: 0
child?: 12907
squire: 0
beside: 0
drowned: 0
unseen: 0
‘wish: 0
sale: 0
frightful: 0
fiend: 0
saying: 0
fix: 0
agree: 0
barrow: 0
slyly: 0
fit: 0
loaded: 0
‘shake: 0
mouse’s: 0
staircase: 0
betimes: 0
immense: 0
‘how?: 0
difficulty: 0
years’: 0
magnificently: 0
scullion: 0
fig: 0
craftily: 0
braided: 0
hunger: 0
golden: 0
more?’: 0
course: 0
fate: 0
design: 0
times: 0
sake: 0
come?: 0
give: 0
benches: 0
thoughtfully: 12907
gasping: 0
goodbye: 0
trips: 0
envious: 0
child: 0
kiss: 12907
praised: 0
whetted: 0
fast: 0
honourably: 0
bottle: 0
understanding: 0
pined: 0
hopped: 0
yearning: 12907
rattled: 0
peril: 0
‘boy: 0
huntsmen: 0
dull: 0
convert: 0
break: 0
‘how: 0
version: 0
anybody: 0
bleed: 0
appear: 0
shabby: 0
mounts: 0
stomach: 0
field: 0
sewed: 0
joint: 0
solicitation: 0
paragraphs: 0
combs: 0
cured: 0
aware: 0
treasures: 0
come: 0
dishes: 0
milking: 0
court: 0
understand?’: 0
waking: 0
gold: 0
sail: 0
search: 0
pleased: 0
golden: 0
anxious: 0
fare: 0
happens: 0
offer: 0
said: 0
goodness: 0
concerning: 0
courtiers: 0
child’s: 0
ashore: 0
here?’: 0
pinch: 0
become: 0
mountain: 0
kindly: 0
condemned: 0
‘cock: 0
decree: 0
oral: 0
fat: 0
master: 0
quite?’: 0
clumsy: 0
elbow: 0
stopping: 0
musicians: 0
earned: 12907
bemoaned: 0
imp?’: 0
ugh: 0
merrily: 0
maiden: 0
spit: 0
wonderful: 12907
roland’s: 0
time: 0
robbery: 0
spin: 0
ended: 0
few: 0
amazed: 0
robbers: 0
whirlwind: 0
hansel’s: 0
bustled: 0
‘full: 0
doves: 0
sunbeams: 0
treatment: 0
‘such: 12907
my: 0
limped: 0
fee: 0
fed: 12907
stepmother: 0
refund”: 0
crosses: 0
disclaimers: 0
shiver: 0
sit?: 0
anything: 0
then?’: 0
torch: 0
waddled: 0
longing: 0
resist: 12907
ridges: 0
crossed: 0
roared: 0
followed: 0
peasants: 0
pockets: 0
went: 0
far: 0
flings: 0
disposed: 0
drink: 0
trusty: 0
hewing: 0
sting: 0
ailed: 0
best: 0
furious: 0
safe: 0
cowardly: 0
added: 0
servants: 0
sprang: 0
pigeons: 0
glass?’: 0
necessity: 0
clearly: 0
roaming: 0
sickness: 0
combing: 0
verily: 0
throughout: 0
dragon: 0
aught: 0
dumplings: 0
music: 0
bodies?: 0
mixed: 0
scratch: 0
see?’: 0
rascal: 0
king: 0
‘surely: 0
kind: 0
heavens: 0
‘will: 0
blowing: 0
freely: 0
express: 0
breach: 0
repeated: 0
lacking: 0
yoked: 0
strong: 0
crevice: 0
loosened: 0
eagerly: 0
hans?’: 0
money: 0
dusty: 0
sprinkle: 0
still: 0
ashputtel: 0
morning: 0
text: 0
seashore: 0
neighbourly: 0
wake: 0
hurts: 0
shut: 0
delicate: 0
suppose: 0
perch: 0
possessed: 0
machine: 0
hood]: 0
pages: 0
nudged: 0
‘elsie: 0
beauty: 0
telling: 0
fat: 0
complained: 12907
far: 0
support: 0
shepherd’s: 0
wretched: 0
mrs: 0
peasant: 0
fountain: 0
kill: 0
‘goodness: 0
fall: 0
raven’s: 0
prince’s: 12907
sack: 0
consented: 0
partnership: 0
enchantment: 0
bread: 0
violently: 0
perching: 0
blossoms: 0
sad?: 0
youth: 0
mrs: 12907
salad: 0
herself: 0
‘home: 0
darling: 0
knowing: 0
winter: 0
identify: 0
flowers?: 0
donations: 0
hurry: 12907
awake: 0
among: 0
excellent: 0
muddy: 0
scanty: 0
swallow: 0
united: 0
sworn: 0
waters: 0
click: 0
mop: 0
reading: 0
fail: 0
meets: 0
happily: 0
mouth: 12907
stays: 0
barrel: 0
particulars: 0
await: 12907
shopkeeper: 0
stroke: 0
backed: 0
fretted: 0
now: 0
daughters?’: 0
vain: 0
chatting: 0
knights: 0
note: 0
hollow: 12907
return: 0
sad: 0
croaked: 0
promising: 0
beasts: 0
according: 0
misfortunes: 0
bent: 0
bend: 0
procure: 0
thirteenth: 0
swiftly: 0
it?’: 0
edge: 0
bridle: 0
through: 0
fairy: 0
hangest: 0
dove?’: 0
stripped: 0
mouse: 0
spindle: 0
title: 12907
nice: 0
involuntarily: 0
tasted: 0
‘listen: 0
comfortably: 0
begged: 0
fair: 0
provision: 0
hearing: 0
dudding: 0
computers: 0
spinning: 0
roving: 0
lump: 0
nose: 0
swore: 0
sword: 0
spat: 0
indeed: 0
trouble: 0
found: 0
innocent: 0
only: 0
ploughed: 0
stops: 0
works: 0
rules: 0
wherewith: 0
seeking: 0
test: 0
frame: 0
worse: 0
little: 12907
ceremony: 12907
amongst: 0
changed: 0
contained: 0
tried: 0
times: 0
o’er: 0
precious: 0
roved: 0
wreath: 0
rapping: 0
water: 0
bell: 0
‘wife: 0
labour: 0
carpenter: 0
meaning: 0
planted: 0
finish: 0
‘madam: 0
sadly: 0
where: 0
not: 0
whilst: 0
receive: 0
‘blessed: 12907
hangman: 0
ashputtel: 0
enough: 0
show: 0
stiff: 0
shot: 0
help: 0
dropping: 0
drew: 0
shop: 0
unenforceability: 0
knight: 0
never: 0
ruled: 0
light: 0
deceive: 0
homewards: 0
arranging: 0
shoe: 0
nicely: 0
grandfather: 0
footing: 12907
ought: 0
croaked: 0
trick: 0
gifts: 0
thunderstorm: 0
sizes: 0
refused: 0
bidden: 0
shoulder: 0
dress: 0
address: 0
govern: 0
happy: 0
feast: 0
crouched: 0
dagny: 0
asleep: 0
skein: 0
overhung: 0
charging: 0
monster’s: 0
‘spinning: 0
district: 0
clung: 0
rubbed: 0
conversation: 0
dinner?’: 0
weighed: 0
suitor: 0
planed: 0
noon: 0
carelessly: 0
prophesy: 0
state: 0
pglaf: 0
shut: 0
needed: 0
rusty: 0
wooer: 0
mount: 0
cheerfully: 0
pity: 0
farthings: 0
fears: 0
king’s: 0
starving: 12907
bridge: 0
schools: 0
amends: 0
assistance: 0
wooed: 0
attendance: 0
kids: 0
‘dearest: 0
downstairs: 0
crumbled: 0
until: 0
punishment: 0
trial: 0
tumble: 12907
jumped: 0
kate: 12907
stick: 0
handful: 0
dusky: 0
none: 0
woods: 0
warm: 0
control: 0
together: 0
knocking: 0
besought: 0
start: 0
stars: 0
dwarf’s: 0
‘it: 12907
crystal: 0
simples: 0
patted: 0
battlefield: 0
fact: 0
screwed: 0
those: 0
trotted: 12907
places: 0
kick: 0
thee?’: 0
naked: 0
espying: 0
eye: 0
considerable: 0
famed: 12907
face: 0
dressing: 0
mid: 0
scratched: 0
covering: 12907
placed: 0
thou: 12907
craftsmen: 0
thorn: 0
hardest: 12907
‘is: 0
lightnings: 0
payments: 0
home?: 0
commands?’: 0
‘most: 0
lives: 0
bandy: 0
rarest: 0
clever: 0
appoint: 0
silver: 0
hinder: 0
constraint: 0
kingdoms: 0
twins: 12907
unhappiness: 0
chamberlain: 0
lived: 0
receipt: 0
txt: 0
mistress: 0
seemly: 0
fickle: 0
considerably: 0
nights: 0
signed: 0
posted: 0
feared: 0
resembled: 0
cleared: 0
trifling: 0
joyful: 0
‘more: 0
silently: 0
thicket: 12907
enchantress: 0
beast’s: 0
release: 0
opening: 0
uniform: 0
reasonable: 0
ship: 0
tell: 0
wood: 0
bees: 0
beer: 0
thicker: 0
richly: 0
been: 0
when: 0
poked: 0
‘hark: 0
sparkling: 0
nuts: 0
scorches: 0
happened?: 0
beef: 0
motion: 0
arose: 0
washing: 0
uncommon: 0
pipe: 0
washed: 0
resound: 0
gets: 0
sections: 0
fetched: 0
ten: 0
place: 0
chuckle: 0
bride: 0
two: 0
trustfully: 0
suffer: 0
beds: 12907
forgot: 0
wages: 0
shines: 0
weeping?’: 0
guard: 0
tremendous: 0
home’: 0
dinners: 0
tom?’: 0
“merrily: 0
overtake: 0
pleases: 0
child?’: 0
journeyed: 0
treasure: 0
grinder: 0
swim: 0
bought: 0
met: 0
blue: 0
shoulders: 0
become: 0
men: 0
stand: 0
live: 0
sleeping: 0
fairly: 0
sacksful: 0
happened: 0
done?: 0
wares: 0
bridal: 0
luck: 0
thanked: 0
roaring: 0
kingdom: 0
pleased: 0
pins: 0
stepmother: 0
purest: 0
pink: 0
november: 0
away: 0
medium: 0
night: 0
remembrance: 0
strength: 0
peeling: 0
fitness: 0
hesse: 0
daylight: 0
witch: 0
liberty: 12907
daughter: 0
running: 0
tender: 0
returning: 0
gravely: 0
bee: 0
born: 0
signal: 0
me?: 12907
home: 0
takes: 0
tub: 0
groaned: 0
ilsabill: 0
done: 0
tease: 0
stall: 0
stuffed: 0
i’ve: 0
pretending: 0
fortress: 0
derived: 0
bones?: 0
exchanged: 12907
“the: 0
get: 12907
reaching: 0
especially: 0
knowledge: 0
kneaded: 0
wolf’s: 0
beat: 0
dragged: 0
yielded: 0
bear: 0
tears: 0
bed: 0
bean: 12907
beam: 0
viewed: 0
beak: 12907
train: 12907
noticed: 0
unsolicited: 0
greatness: 0
information: 0
pile: 0
willingly: 12907
holle: 0
‘mistress: 0
shoulder: 0
cinders: 12907
got?: 0
me: 0
please: 0
trees: 0
greatly: 0
sour: 0
city: 0
valuable: 0
sisters: 0
prize: 0
foretell: 0
soup: 12907
curtain: 0
nailed: 0
‘each: 0
soul: 12907
lost: 0
chamber: 0
pin: 0
wine?’: 0
holiday: 0
naught: 0
cried: 0
copyright: 0
climbed: 0
may: 0
‘stop: 0
garland: 0
‘wait: 0
quickly?: 0
mat: 0
spent: 12907
try: 0
map: 0
worked: 0
gave: 0
man: 0
braying: 0
panes: 0
rings: 0
brightness: 0
suited: 0
who?’: 0
twigs: 0
prison: 0
mad: 0
files: 0
spend: 0
sick: 0
tears: 0
stair: 0
wheel: 0
seizing: 12907
donate: 0
links: 0
permission: 0
skins?’: 0
//www: 0
innocence: 0
little’: 0
sources: 0
you?’: 0
successfully: 0
accordingly: 0
reproached: 0
immediate: 0
dragged: 0
‘countryman: 0
knowall: 0
she: 0
“iron: 0
quickly: 0
blow: 12907
butcher’s: 0
resolved: 0
dipped: 0
forester: 0
touched: 0
drawers: 0
descended: 0
upper: 0
civil: 0
time?”: 0
time?’: 0
needles: 0
choose: 0
‘hullo: 0
concerning: 0
strengthen: 0
surely: 0
animals: 0
supposed: 0
spell: 0
fortune: 0
into: 0
yourself: 0
contrive: 0
legged: 0
because: 0
mornings: 0
sort: 0
valley: 0
paltry: 0
receiving: 0
shrivelled: 0
slipper: 0
plunged: 0
taken: 0
staff: 0
forgetting: 0
in’: 0
‘strew: 0
bucket: 0
anyone: 0
sore: 0
amusement: 0
‘thirdly: 0
mistake: 0
now?’: 0
slipped: 0
clothes: 12907
industrious: 0
succeeded: 12907
brink: 0
bring: 0
end: 0
top: 0
paws: 0
too: 0
fairer: 0
tom: 0
mumbled: 12907
perish: 0
duty: 12907
performing: 0
approaching: 0
curling: 0
toe: 0
earning: 0
overset: 0
circulate: 0
murdered: 0
thyself: 0
length: 0
swam: 0
blessed: 0
trade: 0
section: 0
hurried: 0
seemed: 0
shaved: 0
grandmother: 0
house?’: 0
heated: 0
health: 0
‘why: 0
opportunity: 0
pay: 0
exempt: 0
after: 0
carry: 0
further: 0
stirring: 0
mournfully: 12907
sticks: 0
till: 0
mourning: 0
knew: 0
misfortune: 0
compassionate: 0
2001: 0
track: 12907
giving: 0
twilight: 0
twice: 0
‘put: 0
yet: 0
maids: 0
yourself: 0
swarming: 0
snowflakes: 0
drank: 0
butter: 12907
tear: 0
elf: 12907
managing: 0
starve?’: 0
crept: 0
hopped: 0
forget: 0
bore: 0
soot: 0
morning: 0
sorrows: 0
seaside: 0
delighted: 0
knight: 0
soon: 12907
‘if: 0
suffer: 0
recital: 0
‘stir: 0
dismal: 0
liking: 0
pricked: 0
stepped: 0
prophecy: 0
official: 0
ecclesiastics: 0
unanimously: 0
beating: 0
to: 0
exempt: 0
greater: 12907
these: 0
sons: 0
occasion: 0
variety: 0
pig: 0
fowl: 0
path: 0
home?’: 0
darkness: 0
old: 0
dearest: 0
jeered: 0
song: 0
earth: 0
‘are: 0
bundles: 0
hardly: 0
describing: 0
rude: 0
stitching: 0
punish: 0
past: 0
pass: 0
rocks: 0
dream: 0
impatience: 0
stick: 0
‘at: 0
nodded: 0
thawed: 0
bolted: 0
switzerland: 0
dread: 12907
i’ll: 0
pick: 0
horribly: 0
fastened: 0
displaying: 0
transcription: 12907
some: 0
ein: 0
hostess: 0
maid: 0
sowed: 0
trough: 0
train: 0
inns: 0
which: 0
chestnut: 0
part: 0
tm: 0
singing: 0
king?’: 0
foolish: 0
four: 0
crowned: 0
fox: 0
‘as: 0
park: 0
millers: 0
foul: 0
sold: 0
conscious: 0
poodle: 0
sole: 0
abide: 0
tiled: 0
scent: 0
comforted: 0
pity: 0
kinsmen: 0
linen: 0
stillness: 0
‘bird: 0
costs: 0
ladies: 0
greatest: 0
daily: 0
binds: 0
seven: 0
grasshopper: 12907
speed: 0
flashed: 0
son: 0
tie: 0
command?’: 0
fated: 0
against: 0
assembled: 0
exists: 0
maps: 0
buy?’: 0
thee?: 0
thy: 0
knives: 0
hurrying: 0
hurting: 12907
egg: 0
linked: 0
‘pull: 0
dough: 0
“here: 0
unlink: 0
flocks: 0
dismissed: 0
hedge: 0
thirsty: 0
‘silly: 0
play’: 0
lets: 0
“information: 0
exchange: 0
shoemaker: 0
the: 0
magic: 0
proclaimed: 0
including: 0
begone?’: 0
holder: 0
winged: 0
print: 0
‘and: 0
raise: 12907
cold: 0
godless: 0
dumb: 0
dolefully: 0
played: 0
otherwise: 0
inn: 0
snowdrop’s: 0
betray: 0
round: 12907
depended: 0
all?’: 0
‘see: 12907
blew: 0
false: 0
gudgeons: 0
lament: 0
form: 0
fork: 0
lest: 0
dinner: 0
less: 0
‘whose: 0
bickers: 0
containing: 0
dwell: 0
dwelt: 0
christened?’: 0
incidental: 0
bled: 0
salad: 0
offered: 12907
birches: 0
attracted: 0
coolly: 0
shepherd’s: 0
being: 0
cost: 0
pant: 0
pans: 0
funny: 0
‘scour: 0
behold: 0
often: 0
knelt: 0
‘creep: 0
busily: 0
20%: 0
applicable: 0
‘all: 0
slave: 0
lift: 0
pane: 0
forgetting: 0
burning: 0
particular: 0
joyfully: 0
minute: 0
bonnet: 0
winter: 0
for?: 0
prohibition: 0
wisest: 0
‘bind: 0
swimming: 0
deeds: 0
sent: 0
dukes: 0
ten: 0
speak: 0
finding: 0
bride: 0
‘where: 0
rumpelstiltskin: 0
haughty: 0
dwelling: 0
‘stay: 0
cave: 0
whistling: 0
porch: 0
brass: 0
teach: 12907
let: 0
neighbourhood: 0
impossible: 0
will?: 0
infringement: 0
related: 0
shanks: 12907
kills: 0
wedding: 0
colours: 0
character: 12907
slopping: 0
dismissal: 0
‘could: 0
chicks: 0
early: 0
foot: 0
surprised: 0
prudently: 12907
soft: 0
for: 0
earls: 0
reality: 0
fool: 0
ebook: 0
pale: 0
remorse: 0
emptied: 0
silver?’: 0
included: 0
‘all: 0
saving: 0
food: 0
doubt: 0
thousands: 0
comical: 0
sentenced: 0
topmost: 0
ebony: 0
cats: 0
actual: 0
making?: 0
distribution: 0
quench: 0
font: 0
provided: 0
nickname: 0
raspberry: 0
printed: 0
brilliant: 0
‘there’s: 0
gratefully: 0
you’re: 0
‘coxcomb: 0
stromberg: 0
previous: 0
painter: 0
eat: 0
slice: 0
ear: 0
fond: 0
smaller: 12907
lina: 0
sudden: 12907
briar: 0
outside: 0
inward: 0
merciful: 0
dog’s: 0
painted: 0
cast: 0
includes: 0
org/donate: 0
flashing: 0
dead?’: 0
handsomer: 0
merriment: 0
tax: 0
cask: 0
much: 0
tan: 0
forest?: 0
intending: 0
joyously: 0
case: 0
lent: 0
thirdly: 0
for?’: 0
‘why?’: 0
folk: 0
forsake: 0
wood?’: 0
sorrowed: 0
standing: 0
whereupon: 0
‘aha: 0
bites: 0
man’s: 0
figure: 0
family?’: 0
kill: 0
cart: 0
kettle: 0
request: 0
wiser: 0
tap: 0
pair: 12907
‘feel: 0
dripping: 0
pain: 0
soon: 0
pail: 12907
fly’s: 0
peacefully: 0
forest: 0
care: 0
card: 0
supported: 0
sock: 0
paid: 0
fish: 0
something: 0
outwitted: 0
tired: 0
dismounted: 0
have?’: 0
vain?: 0
first?: 0
falls: 0
renowned: 0
awaken: 12907
determine: 0
rough: 0
enjoy: 0
cat: 12907
is’: 0
brought: 0
awoke: 0
merchant: 0
pray: 0
quite: 0
low: 0
grieves: 0
lot: 0
rattled: 0
years: 0
numerous: 0
myself: 12907
limitation: 0
his: 0
beware: 0
paperwork: 0
log: 0
fainting: 0
hill’s: 0
grieved: 0
endured”: 0
knees: 12907
giving: 0
first: 0
org/fundraising: 0
page: 0
gangest: 0
dug: 0
contented: 0
drunken: 0
heroic: 0
front: 0
healed: 0
popped: 0
died?’: 0
touching: 0
starve: 0
each: 0
‘brother: 0
century: 0
depart: 0
satisfy: 0
father: 0
necessarily: 0
therein: 0
honest: 0
workshop: 0
slept: 0
melan: 0
little: 0
shudder: 0
contrast: 0
‘give: 0
expected: 0
year: 0
overrun: 0
consent: 0
holle: 0
duck: 0
useful: 0
‘you’re: 0
edwardes: 0
boy’s: 12907
reeds: 0
fall: 0
scissor: 0
99712: 0
‘fear: 0
‘when: 0
pride: 0
pierced: 0
raging: 12907
archive: 0
counselled: 0
copied: 0
hind: 0
elsie’s: 0
‘till: 0
essential: 0
echoed: 0
codes: 0
children’s: 12907
split: 0
copies: 0
property: 0
sacks: 0
among: 0
alive: 0
‘certainly: 0
prick: 0
burst: 0
‘that: 0
astonished: 12907
capering: 0
cap: 0
price: 0
apples?’: 12907
corporation: 0
cellar: 0
1812: 0
stove: 0
odd: 0
announced: 0
willing: 0
beast: 0
came: 0
scattered: 0
goodness’: 0
remaining: 0
‘alas: 0
wrens: 0
greens: 0
wooden: 0
shining: 0
observed: 0
ducks: 0
ground: 0
stout: 0
stool: 0
imposed: 0
waddling: 0
stripes’: 0
way?’: 0
hill: 0
benjamin: 0
calm: 0
call: 0
graciously: 0
starry: 0
opposite: 0
noises: 0
him?: 0
calf: 0
unfit: 0
malice: 0
legs: 12907
pace: 0
recognize: 0
seeing: 0
branches: 0
presents: 0
1887: 0
number: 0
growing: 0
harness: 12907
from: 0
beard: 0
lit: 0
amused: 0
fields: 0
project: 0
servant’s: 0
fellows: 0
can: 0
advice: 0
scrape: 0
gold?’: 0
disappeared: 0
guards: 0
liquor: 0
scalded: 0
boastfully: 0
immediately: 0
cake: 0
left: 0
grimm: 0
stitches: 0
married: 0
out?’: 0
any: 0
approached: 0
high: 0
spiteful: 0
fundevogel: 0
aged: 0
bewitched: 0
‘where’s: 0
stitched: 0
‘what: 0
‘bless: 0
him: 0
amuse: 0
sorrowfully: 0
ourselves?’: 0
‘thank: 0
dearest: 0
lie: 0
lid: 0
roguish: 12907
‘don’t: 0
‘his: 0
witch’s: 0
noise?: 0
licking: 0
overtook: 0
story: 0
leisure: 0
kids: 0
editions: 0
jacob: 0
due: 0
duck: 0
straight: 0
ebooks: 0
refresh: 0
polluted: 0
knowing: 0
storm: 0
passages: 0
quilt: 0
passing: 0
ants: 0
untying: 0
wicked: 0
store: 0
‘how: 0
bills: 0
‘you’ll: 0
o’clock: 0
shell: 0
matter?’: 0
bear: 0
tossed: 0
amuse: 0
piece: 0
choose: 0
frogs: 0
pedlar: 0
troop: 0
shame’: 0
talks: 0
shelf: 0
ante: 0
field: 0
enter: 0
buzzed: 0
clothes: 0
early: 0
landmark: 0
noise: 0
clothed: 0
fellow: 0
“here: 0
alight: 0
alive?’: 0
holes: 0
bestow: 0
easy?’: 0
anything: 0
beans: 0
glee: 0
life: 0
about?: 0
millstone: 0
constant: 0
child: 0
decide: 0
fresh: 0
‘hush: 0
hawk: 0
enchantment: 0
wanderer: 0
fulfilled: 0
bewail: 0
mist: 0
embraced: 0
pitch: 0
picked: 0
wondered: 0
school: 0
prisoners: 0
swimming: 0
playing: 0
wren: 0
earth: 0
high: 0
asses: 0
2591]: 0
upon: 12907
frog?: 0
foam: 0
do?’: 0
cage: 0
hither: 0
upon: 0
indoors: 0
marshal: 0
cages: 0
proper: 0
jorindel: 0
wandered: 0
calves’: 0
cleft: 0
let: 0
miss: 0
spangled: 0
think: 0
tall: 0
bargains: 0
dug: 0
stoop: 0
forthwith: 0
falada: 0
stool: 0
have: 0
scorching: 0
leg: 0
renewed: 0
led: 0
‘justice: 0
catching: 0
stood: 0
promised: 0
stared: 0
specified: 0
hungry: 12907
leap: 0
hosts: 0
loudly: 0
led: 0
crackle: 0
lean: 0
afraid: 0
‘standing: 0
pears: 0
things: 0
‘open: 0
nightingale: 0
frog: 0
leaf: 0
lead: 0
fast: 0
caves: 0
cheated: 0
splendid: 0
grain: 0
rapunzel: 0
sun: 0
sum: 0
dummling: 0
hart: 0
stone: 0
mischance: 0
shrill: 0
ducat: 0
mysterious: 0
rendered: 0
literary: 0
bean: 0
‘anything: 0
replied: 0
secret: 0
hereupon: 0
liquid: 0
pointed: 0
beaten: 0
﻿the: 0
sty: 0
scolding: 0
granted: 0
frock: 12907
themselves: 0
mite: 0
hath: 0
scholarly: 0
weep?: 0
twelve: 0
hide: 0
discontinue: 0
hold: 12907
cannot: 0
clutched: 0
killed: 0
smacked: 0
informed: 0
dry: 0
boldly: 0
gardens: 0
glad: 0
grave: 0
that?’: 0
law: 0
pearl: 0
hast: 0
parlour?’: 0
wound: 0
emperor?: 12907
childless: 0
ascending: 12907
hick: 0
promise: 0
unruly: 0
whence: 0
timothy: 0
coughing: 0
bargain: 0
alike: 0
evil: 0
danced: 0
betrayed: 0
rocking: 0
merely: 0
overwhelmed: 0
dawdle: 0
sighing: 0
stole: 0
‘keep: 0
does: 0
cow’s: 0
greedy: 0
enticed: 12907
ilsabill: 0
villages: 0
scolded: 0
burden: 0
lay: 0
snug: 0
grief: 0
hoarse: 0
scissors: 0
thing: 0
emperor: 0
tales: 0
harm: 0
lap: 0
whosoever: 0
delay: 0
wait: 0
hare: 0
ambush: 0
chimney: 0
whatever: 12907
hard: 0
gretel: 0
quiet: 0
nearly: 12907
lad: 0
stoke: 0
mistook: 0
internal: 0
peas: 0
volumes: 0
sheer: 0
bestir: 0
sheep: 0
1863: 0
prying: 0
cudgelled: 0
2591: 0
would: 0
open?: 0
clear: 12907
leaped: 0
decided: 0
clean: 0
brother: 12907
hid: 0
bed?’: 0
coined: 0
king’s: 0
grass: 0
tugging: 0
lands: 0
window: 0
stood: 0
accident: 0
while?’: 0
unicorn: 0
‘because: 0
‘iron: 0
ween: 0
garden: 0
miserably: 0
weeks: 0
spy: 12907
chief: 0
innocent: 0
doo: 0
thriven: 0
has: 0
‘why: 12907
again: 12907
man?’: 0
alive: 0
nuts: 0
1859: 0
perished: 0
dog: 0
there?: 0
‘who: 0
pursue: 0
1814: 0
miserable: 0
refused: 0
unhappily: 0
those: 0
merchant: 0
excuses: 0
spoiled: 0
taste: 0
quick: 0
parlour: 0
‘rapunzel: 0
sulky: 0
richly: 0
guarded: 0
finding: 0
astonishment: 0
fewer: 0
‘something: 0
‘gave: 0
contract: 12907
passes?: 0
fright: 0
i’m: 0
mouthful: 0
son: 0
open: 0
do?: 0
asked: 0
forgets: 0
hiding: 0
‘out: 0
locks: 0
chase: 0
rumpelstiltskin?’: 0
‘whatever: 0
entire: 0
first: 0
wakened: 0
friend?’: 0
hidden: 0
stirred: 0
cracked: 0
hans: 0
so?: 0
louder: 0
finished: 0
savage: 0
‘neither: 12907
locks: 0
started: 0
mine: 0
mind: 0
hang: 0
charm: 0
hand: 0
ghost: 0
land: 0
trample: 12907
very: 0
sticking: 0
chop: 0
majesty: 0
strangle: 0
‘our: 0
mounted: 0
mother: 12907
insists: 0
shed: 0
suddenly: 0
higher: 0
treachery: 0
hornets: 12907
do: 0
bargained: 0
neglected: 0
donors: 0
father: 0
beckoned: 0
bucketful: 0
doublet: 0
rapid: 0
wiped: 0
careful: 0
befell: 0
windowframe: 0
shouting: 0
snow: 0
frolic: 0
1823: 12907
mouths: 0
adventures: 0
countless: 0
movements: 0
‘take: 0
none: 0
frankfurt: 0
grimms’: 0
eyes: 0
across: 0
bolder: 0
wishing: 0
partlet: 0
crossing: 0
keeping: 0
mill: 0
milk: 12907
hall: 0
dreary: 0
quarters: 0
mile: 0
copper: 12907
grant: 0
half: 0
so: 0
clambered: 0
busybody: 0
queen’s: 0
simpletons: 12907
there: 0
hero: 0
forget: 0
walled: 0
dispute: 0
catches: 0
flames: 0
‘back: 0
befriended: 12907
‘he: 0
grand: 0
easily: 0
outdated: 0
girls: 0
online: 0
sixty: 0
‘come: 0
surface: 0
sky: 0
upright: 0
entrance: 0
pitied: 0
‘prince: 12907
pity’s: 0
lamb’s: 0
treated: 0
linger: 0
‘has: 0
swung: 0
sixth: 0
‘never: 0
darker: 0
shoemaker’s: 0
plate?’: 0
nearer: 0
experience: 0
workmen: 0
understand: 0
mankind: 0
younger: 0
spirit: 0
dim: 0
above: 0
waiting: 0
single: 0
deny: 0
despite: 0
dig: 0
gasping: 12907
die: 0
did: 0
havoc: 0
entreaties: 0
stock: 0
cooks: 0
another: 0
frightened: 0
about: 12907
consumed: 0
alarm: 0
honourable: 0
proclaim: 0
willingly: 0
looked: 0
believe: 12907
exception: 0
pitchers: 0
hair: 0
defective: 0
bewail: 0
powerful: 0
six: 0
‘was: 0
sit: 0
simpleton: 0
sir: 0
smelt: 0
might: 0
sin: 0
waves: 0
presence: 0
pebble: 0
embroidered: 0
smell: 12907
tempted: 0
rest: 0
discourse: 0
night’s: 0
roasted: 0
struck: 0
consulted: 0
hunger: 0
riches: 0
richer: 0
sooner: 0
‘must: 0
payments: 12907
chalk: 0
peeped: 0
sitting: 0
depends: 0
notice: 0
justice: 0
joined: 0
chin: 0
prince’s: 0
she: 0
behaviour: 0
yourselves: 0
cobbler: 0
english: 0
hasten: 0
very: 0
dashed: 0
engraved: 0
seated: 0
edition: 0
gorged: 0
asleep’: 0
gossip: 0
tasks: 0
dreamt: 12907
brown: 0
dreams: 0
want’: 0
practically: 0
sorely: 0
grain: 12907
wilhelm: 0
disenchanted: 0
chandelier: 0
snip: 0
endless: 0
may: 0
dew: 0
asked: 0
stranger: 0
knife: 0
surrounded: 0
limbs: 0
‘money: 0
thus: 0
charge: 0
den: 12907
pitcher: 0
pinched: 0
possession: 0
pope: 0
‘since: 0
‘strike: 0
‘one: 0
obeyed: 0
fruits: 0
midges: 0
sons: 0
combed: 0
stationed: 0
poor: 0
betrothed: 12907
and: 0
wreaths: 0
pool: 0
facility: 0
sew: 0
‘nursery: 0
repair: 0
smiled: 12907
chair: 0
set: 0
chain: 0
fowls: 0
repaid: 0
shuddering: 0
see: 12907
cows: 0
appearing: 0
shrank: 0
sea: 0
strokes: 0
always: 0
behind: 0
weather: 12907
‘nibble: 0
mate: 0
would?’: 0
peace: 0
dainty: 12907
pond: 0
unwillingly: 12907
brooch: 0
‘old: 0
capered: 0
paths: 0
dream: 0
companion: 0
broth: 0
mass: 0
risk: 0
returned: 0
farmer: 0
singer: 0
ringing: 0
pomp: 0
rise: 0
locked: 0
here?: 0
vent: 0
unbound: 0
hack: 0
menial: 0
mice: 0
thoughtful: 0
ascend: 0
rogues: 12907
thumb: 0
scampered: 0
couple: 0
welcome: 0
brightly: 0
replace: 0
‘heaven: 0
day: 0
lord: 0
mark: 0
silent: 0
troublesome: 12907
‘even: 0
game: 0
pennies: 12907
beasts: 0
laugh: 0
usual: 0
krr: 0
distribution: 0
trademark: 0
watered: 0
kitchen: 0
miller’s: 0
murdering: 0
herbs: 0
here: 0
obtaining: 0
rueful: 0
tying: 0
miau: 0
cause: 0
battle: 12907
bathing: 0
fling: 0
‘those: 0
corrupt: 0
poke: 12907
arrogance: 0
fished: 0
had: 0
say: 0
wisdom: 0
saw: 0
fishes: 0
search: 0
sat: 0
around: 0
fires: 0
grace: 0
deer: 0
prettily: 0
deep: 0
working: 0
because: 12907
thanks: 0
‘murder: 0
maps: 0
throughout: 0
followed: 0
cost: 0
comrade?’: 0
sad: 12907
nails: 0
deed: 0
stumbles: 0
miraculous: 0
‘where: 0
ripe: 0
periodic: 0
sunday: 0
‘oho: 12907
sleeping: 0
sensibly: 0
current: 0
point: 12907
tossing: 0
library: 0
balls: 0
ropemaker’s: 0
‘thou: 0
strange: 0
observe: 0
chat: 0
bearskin: 0
chap: 0
uneasiness: 0
useful: 0
try: 0
distributing: 0
‘never: 0
critical: 0
threshold: 0
corn: 0
‘lay: 0
broom: 0
moving: 0
‘lift: 0
christened: 0
called: 0
behaved: 0
knocked: 0
cord: 0
“under: 0
marleen: 0
ball?: 0
towns: 0
‘fundevogel: 0
have?: 0
esteemed: 0
edwardes: 0
many: 0
brook: 0
bees’: 0
reverence: 0
plucking: 0
deck: 0
mother: 0
snap: 0
brood: 0
mayor: 12907
patch: 0
stronger: 0
bushes: 0
cooked: 0
ring: 0
cock: 0
cavern: 12907
sensible: 0
boats: 0
true: 0
neither: 0
nobleman: 0
different: 0
sure: 0
afternoon: 0
michael: 0
most: 0
listening: 0
backwards: 0
manikin: 0
copy: 0
fire: 0
highest: 0
prove: 0
boxes: 0
korbes’s: 0
man?: 0
confessed: 0
knocks: 0
coming: 0
merry: 0
well: 0
curled: 0
have: 0
influenced: 12907
boast: 0
org: 0
haughtily: 0
spoilt?’: 0
crying: 0
i?’: 12907
trumpets: 0
legitimate: 12907
‘late: 0
fitted: 0
strewn: 0
underwood: 12907
dear: 0
ball: 0
stayed: 0
fork?’: 0
goldsmith: 0
skulls: 0
deal: 0
curiosity: 0
hearty: 0
proud: 0
exporting: 0
foundation: 0
transformation: 0
hearts: 0
dead: 0
holding: 0
placed: 0
interrupted: 0
cool: 0
cook: 0
cleverness: 0
creatures: 0
unfastened: 0
learning: 0
hearth: 0
other: 0
german: 0
behaved: 0
whispering: 0
deserve: 0
lamps: 0
once: 0
board: 0
former: 0
tongue: 0
separate: 0
‘thou: 0
pudding: 0
friendship: 0
man: 0
hans: 0
dispatched: 0
brighten: 0
brighter: 0
letters: 0
formed: 0
queen: 12907
splash: 0
make: 0
moment: 0
warlike: 0
boat: 0
hearse: 0
wealth: 0
lamenting: 0
begins: 0
measure: 0
fiery: 0
‘yonder: 12907
brushwood: 0
spending: 0
its: 0
remember: 0
backward: 0
broke: 0
sung: 0
ovenful: 0
awful: 0
crowns: 12907
‘tonight: 0
derive: 0
gather: 0
cinder: 0
sunk: 0
remarked: 0
house?’: 0
butter: 0
come: 0
electronic: 0
wolf’: 0
comb: 0
rays: 0
need: 0
companies: 0
forest: 0
‘this: 0
stepdaughter: 0
‘when: 0
musician: 0
prettier: 0
reflection: 0
main: 0
heart: 0
mail: 0
provide: 0
nurse: 0
hounds: 0
running: 0
fattening: 12907
maid: 0
apron?’: 0
silly: 12907
cold: 0
cords: 0
buyers: 0
grateful: 0
insolence: 0
indemnity: 0
until: 0
snips: 12907
impetuous: 0
official: 0
kid: 0
clouds: 12907
guilty: 0
redistribute: 0
parents: 0
pantry: 0
daughter’s: 0
thorns: 0
proposition: 0
imagine: 0
length: 0
bruised: 0
bargain: 0
abode: 12907
south: 12907
trod: 0
quails: 12907
‘stand: 0
tired: 0
father’s: 0
anvil: 0
loveliest: 0
flies: 0
begin: 0
written: 0
outer: 0
confirmed: 0
zip: 0
format: 0
permanent: 0
sun: 0
just: 0
dived: 0
woman: 0
‘sitting: 0
girdle: 0
handed: 0
particularly: 0
woodman: 12907
‘god: 0
anxiety: 0
proof: 0
woman: 0
unable: 0
letter: 0
beauteous: 0
sad?’: 0
dreadful: 0
‘here: 0
marburg: 0
night?’: 0
good?’: 0
sparrows: 0
trampling: 0
coin: 12907
danger: 0
moaning: 0
settle: 0
courtyard: 0
cur: 0
assumed: 0
suit: 0
leave: 0
furs: 0
‘they: 12907
hansel: 0
flask: 0
sorrowful: 12907
wanting: 0
fox?: 0
butcher: 0
fury: 12907
tower: 0
caring: 0
dishful: 0
afar: 0
‘then: 0
brew: 0
towel: 0
‘gently: 0
rolls: 0
stable: 0
excellence: 0
cut: 0
overjoyed: 0
key: 0
magnificent: 0
cup: 0
contain: 0
panting: 0
borrowed: 0
wits: 0
eventide: 0
neither: 0
stool?’: 0
fools: 0
bred: 0
809: 0
medicine: 0
801: 0
with: 0
espied: 0
howl: 12907
tooth: 0
next: 0
been?’: 0
rate: 0
people: 12907
tomorrow: 0
wounded?’: 0
ride: 0
utterly: 0
right: 0
know: 0
made: 0
ahead: 0
gates: 0
rub: 0
pillows: 12907
news: 0
rick: 0
mishap: 0
collar: 0
least: 0
willows: 0
run: 0
‘before: 0
wish: 0
purple: 0
watch: 0
wise: 12907
stones: 0
minds: 0
unbidden: 0
rue: 12907
unable: 0
crawl: 0
boiled: 0
rich: 0
kicks: 0
doing?’: 0
calculated: 0
dismay: 0
awaiting: 0
blessing: 0
undertake: 0
sinner: 0
waited: 0
going: 0
horse: 0
rare: 0
boughs: 0
cabbages: 0
bought: 0
partnership: 0
hour: 0
billows: 0
‘the: 0
anyone: 0
trip: 0
hangs: 0
cry: 0
grows: 0
suppers: 0
trim: 0
offers: 12907
quench: 0
quacking: 0
eleven: 0
grown: 0
sparrow: 0
learn: 0
owner: 0
demand: 0
doodle: 0
laughed: 0
sound: 0
sprung: 0
ceasing: 0
1785: 0
1786: 0
gudgeons: 0
‘that: 0
how: 12907
shoemaker: 0
seventh: 0
wailing: 0
‘than: 0
fascinated: 0
seen: 0
vanilla: 0
cries: 0
apiece: 0
shudder: 0
instantly: 0
hurricane: 0
seems: 0
enraged: 0
majesty: 0
magic: 0
takes: 0
concert: 0
contact: 0
gate: 0
cried: 0
grove: 0
taken: 0
concern: 0
crowed: 0
host: 0
eleven: 0
crawled: 0
renders: 0
derry: 0
punished: 0
sounding: 0
willow: 0
wipe: 0
healing: 0
entreaty: 0
broad: 0
group: 0
returns: 0
new: 0
stone: 0
leapt: 0
league: 0
‘twas: 0
badly: 0
cock: 0
sausages: 0
concept: 0
gothel: 0
muttering: 12907
newsletter: 0
there’s: 0
unexpected: 0
it?’: 0
fastest: 0
volunteers: 0
grow: 0
son’s: 0
stirred: 0
‘after: 0
magical: 0
river: 0
flame: 0
horn: 0
finger: 0
afterwards: 0
nest: 0
hands: 0
silenced: 0
hang: 0
cow: 0
despair: 0
crash: 0
supper: 0
full: 0
grow: 0
struggling: 0
seeks: 0
suck: 0
tumbling: 0
‘carter: 0
people: 0
such: 12907
fluttered: 0
masters: 0
trademark/copyright: 12907
rolled: 0
rank: 0
wants: 0
wing: 0
squire’s: 0
contributions: 0
wine: 0
wind: 0
rang: 0
coat: 0
gross: 0
judge: 0
anywhere: 0
horns: 0
brayed: 0
mercy: 0
‘took: 0
coal: 0
regarded: 0
yellow: 0
tree: 0
ambassador: 0
certainly: 0
knit: 0
row: 12907
take: 0
hanau: 12907
offer: 0
birth: 0
nevertheless: 0
gladness: 0
‘softly: 0
lambs: 0
contentedly: 0
proofread: 0
roe: 12907
prominently: 0
swept: 0
‘get: 0
rod: 0
hope: 0
rob: 0
fourteen: 0
crowd: 0
eaters: 0
me?’: 0
pushed: 0
friends: 0
return: 0
tarry: 0
sausage: 0
wilt: 0
horseback: 0
crumbs: 0
frozen: 0
abashed: 0
strangers: 0
many: 0
tm’s: 0
will: 0
servants?’: 12907
valiant: 0
journeying: 0
uttered: 0
himself: 0
they: 0
wild: 0
hook: 0
ascended: 0
hand: 0
repose: 0
streamed: 0
huntsmen’s: 0
student’s: 0
tonight: 0
oneself: 0
breathed: 0
begun: 0
errand: 0
chose: 0
amid: 0
cursed: 12907
florins: 0
eats: 0
broomstick: 12907
prospered: 0
elbows: 0
basted: 0
master: 0
heart’s: 0
ran: 0
helped: 0
doing: 0
report: 0
rake: 0
wheels: 0
back?’: 0
suspected: 0
evening: 0
wedge: 0
diamonds: 0
unlock: 0
possess: 0
wherever: 0
smoking: 0
easy: 0
comply: 0
indemnify: 0
scarcely: 0
glimmer: 0
east: 0
maid’s: 0
street: 0
nonsense: 0
unknown: 0
answered: 0
forth: 0
persons: 0
happened: 12907
reckoning: 0
‘seven: 0
curdken’s: 0
stairs: 0
truth: 0
ordering: 0
ease: 0
landlord: 0
trap: 0
walked: 0
“heads: 0
motionless: 0
home: 12907
she’s: 0
millstone: 12907
butler: 0
ways: 0
elves: 0
groom: 0
knew: 12907
shudder?’: 0
“plain: 0
sackful: 0
trust: 0
ears: 0
rampion: 0
steep: 0
food: 0
snorted: 0
earn: 0
aloud: 0
fox’s: 0
rain: 12907
whenever: 0
going?’: 0
english: 0
knee: 0
diligent: 0
goats: 0
grim: 0
farmyard: 0
quickly: 0
‘bravo: 0
hole: 0
hold: 0
heard: 12907
these: 0
faces: 0
foolishly: 0
sitting: 0
yourself?’: 0
between: 0
slowly: 0
‘round: 0
‘false: 0
wights: 0
marched: 0
eat: 0
fancies: 0
took: 0
faced: 0
pinafore: 0
doublet: 12907
baker’s: 0
barons: 0
watches: 0
water’s: 0
nothing: 0
rumbles: 0
fancied: 12907
fuel: 0
upstairs: 0
there: 0
walking: 0
relented: 12907
launched: 12907
underneath: 0
cursing: 0
reigned: 0
fruit: 0
began: 0
watched: 0
together: 0
passed: 0
rags: 0
their: 0
//pglaf: 0
rip: 0
face?: 12907
silvery: 0
rim: 0
grounds?: 0
cudgel: 0
types: 0
fierce: 0
godmother: 0
rage: 0
‘nonsense: 0
rid: 0
fared: 0
rib: 0
filthy: 12907
pretty: 0
poisoned: 0
catch: 0
based: 0
way: 0
spruce: 0
strangely: 0
butterflies: 12907
escape: 0
‘whither: 0
fortunately: 0
natural: 0
‘bride: 0
wave: 0
displayed: 0
stream: 0
within: 0
streak: 0
seed?: 0
instant: 0
wife: 0
snored: 0
modestly: 0
meadows?’: 0
scrambled: 0
‘now: 0
cease: 0
‘not: 12907
“it: 0
eaten: 0
illustration: 0
tidings: 0
bade: 0
bridegroom: 0
thresholds: 0
grey: 0
‘early: 0
cheese: 0
grew: 0
fast?’: 0
favour: 0
entirely: 0
swallowed: 0
gregory: 0
perform: 12907
feigning: 0
ridiculed: 0
specific: 0
skipping: 0
her?’: 0
ranged: 0
‘good: 0
mouse: 0
‘nothing: 12907
business: 0
handling: 0
odious: 0
financial: 0
‘it’s: 0
‘your: 0
000: 0
fare: 0
trunk: 0
complying: 0
wide: 0
ascii”: 0
“jip: 0
yet?’: 0
meeting: 0
thrice: 0
remained: 0
flapping: 0
haired: 0
leads: 0
hampered: 0
ridden: 0
marrying: 12907
pope?: 0
chattering: 0
lamented: 0
admitted: 0
ill: 0
thieving: 0
wash: 0
meantime: 0
musicians: 0
villain: 0
public: 0
mission: 0
sewn: 0
jug: 0
move: 0
rack: 0
proved: 0
‘uncouth: 0
rained: 0
snake: 0
tresses: 0
principally: 0
wither: 0
red: 0
wars: 0
climbed: 0
wanted: 0
qualities: 0
“i: 12907
ware: 12907
fetched: 0
declare: 0
truly: 12907
ugly: 0
military: 0
warn: 0
warm: 0
maidens: 0
hoes: 0
stepped: 0
walking: 0
principal: 0
along: 0
alone: 0
spray: 0
possible: 0
craft: 0
baskets: 0
fully: 0
missing: 12907
sweet: 0
sweep: 0
include: 0
plight: 0
princesses: 12907
straitened: 0
quietly: 0
pertains: 0
lathe: 0
quicker: 0
‘behave: 0
scoundrel: 0
grandmother’s: 0
prove: 0
caw: 0
increased: 0
chambers: 0
rings: 0
snail: 0
briar: 0
“what: 12907
‘you: 0
request: 0
thief?: 0
boiling: 0
stump: 0
temptation: 0
then: 0
village: 0
moss: 0
goals: 0
smells: 0
nightingales: 0
mightily: 0
task?’: 0
discern: 0
‘pray: 0
cat: 0
unbolted: 0
eager: 0
so?’: 0
cap: 0
can: 0
most: 0
was: 0
avail: 0
travel: 0
need: 0
came: 0
shall: 0
snarled: 0
smiled: 0
later: 0
chairs: 0
gathered: 0
trifle: 0
said: 0
possession: 0
compilation: 0
full: 0
them: 0
original: 0
poisoned?: 0
‘yellow: 0
[ebook: 0
should: 0
plaything: 0
blythe: 0
ray: 0
pretend: 0
unbeaten: 0
come?’: 0
became: 0
cage’: 0
arrived: 12907
fireplace: 0
begin: 0
hansel: 0
wretchedness: 12907
[little: 0
fisherman: 0
stately: 0
maiden: 0
rap: 0
disfigure: 0
ran: 0
more: 0
their: 0
‘just: 0
shewed: 0
afterwards: 0
son’s: 0
commands: 0
tobacco: 0
later: 0
following: 0
crack: 12907
want: 0
leaves: 0
glittered: 0
neck: 0
blind: 0
fourth: 0
delicious: 0
manages: 0
hunting: 0
crabs: 0
overcome: 0
baker: 0
distinguished: 0
poisoned: 0
chamber: 0
beautifully: 0
registered: 0
loins: 0
wand: 0
roland: 0
mocked: 0
deserves: 0
managed: 0
patient: 0
dislike: 0
sweat: 0
summon: 0
road’: 0
joy: 0
gathered: 0
bitterly: 0
everyone: 0
birds: 0
cheeks: 0
crabb: 0
provided: 0
dropped: 0
judged: 12907
year’s: 12907
leisurely: 0
neat: 0
royalty: 0
“ah: 0
screw: 0
leaves: 12907
set: 0
chair: 0
gone’: 0
nobody: 0
son?’: 0
job: 0
prayed: 0
undone: 0
falling: 0
near: 0
meal?’: 0
services: 0
lived: 0
fighting: 0
roses: 0
mortal: 0
latch: 0
coffin: 0
notes: 0
wall: 0
walk: 0
moon: 0
settled: 0
meanwhile: 0
chains: 0
sprouted: 0
traitors’: 0
you: 12907
mood: 0
remain: 0
cutting: 0
firewood: 12907
negligence: 0
curious: 0
sorcerer: 0
tangled: 0
leave: 0
‘from: 0
flask: 0
confidential: 0
unconsumed: 0
huntsmen?’: 0
‘perhaps: 0
threaten: 0
second: 0
wagged: 0
sell: 0
booty: 0
wake: 0
croaking: 0
poison: 0
boots: 0
rode: 12907
pick: 0
dove?’: 0
judge: 0
frighten: 0
blaze: 0
leant: 0
bird’s: 0
bound: 0
quieted: 0
“good: 0
published: 0
formats: 0
bird: 0
performances: 0
unwrapped: 0
limped: 0
eagerness: 0
conscience: 0
torches: 12907
married: 0
sent: 0
countries: 0
chatting: 12907
called: 0
‘don’t: 0
daytime: 0
simple: 0
each: 0
adventure: 0
‘only: 0
‘yes’: 0
pitiful: 0
wait: 0
send: 0
settle: 0
‘master: 0
stop: 0
curtains: 0
surrounded: 12907
thee?: 0
rose: 0
heart?’: 0
days’: 0
gradually: 0
perceived: 0
note: 0
fifteenth: 0
perfectly: 12907
flying: 0
suspecting: 0
begging: 0
unto: 0
braying: 0
industry: 12907
mockingly: 0
stepsister: 0
refuse: 0
peasant’s: 0
decision: 0
harmless: 0
not?’: 12907
whither: 0
merry: 0
consequence: 0
study: 0
tacked: 0
conceive: 0
true: 0
ended: 0
gallows: 0
senseless: 0
horsemen: 12907
sell: 0
profits: 0
accepted: 0
soothe: 0
‘lord: 12907
self: 0
‘nay: 0
shared: 0
such: 0
underneath: 12907
studied: 0
brains: 0
puts: 0
began: 0
jip: 0
everything: 12907
baker: 0
fox?’: 0
proceeds: 0
few: 0
wolf: 0
manage: 12907
distribute: 12907
rapunzel’s: 0
jib: 0
